### ISSUE TITLE
v1.7.0-beta.6 , nothing working

### ISSUE THREAD

**Issue by Magna66** [0x5e/homebridge-tuya-platform#147]
ERROR LOADING PLUGIN @0x5e/homebridge-tuya-platform:
[12/14/2022, 12:17:43 PM] Error: Cannot find module 'hap-nodejs'
Require stack:
- /homebridge/node_modules/@0x5e/homebridge-tuya-platform/dist/util/TuyaStreamDelegate.js
- /homebridge/node_modules/@0x5e/homebridge-tuya-platform/dist/accessory/CameraAccessory.js
- /homebridge/node_modules/@0x5e/homebridge-tuya-platform/dist/accessory/AccessoryFactory.js
- /homebridge/node_modules/@0x5e/homebridge-tuya-platform/dist/platform.js
- /homebridge/node_modules/@0x5e/homebridge-tuya-platform/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/util/TuyaStreamDelegate.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/CameraAccessory.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)

Cant even get back to v1.7.0-beta.5.
Managed to get back to v1.7.0-beta.5, by running this command in terminal npm install @0x5e/homebridge-tuya-platform@v1.7.0-beta.5.
Anyway beta6 is not working at all, not even running in homebridge, thus all devices and scenes are gone. Thank you for your great effort really appreciate that plugin. Hope that you fix beta6, and waiting for the support of the IR devices. Really a great work.

**Comment by 0x5e** [comment]
Please try v1.7.0-beta.7, sorry for the inconvenience.

**Comment by Magna66** [comment]
Yup beta 7 working fine. Thank you so much for your great work, and prompt action. You are a great a man 0x5e. Really excellent job.
