### ISSUE TITLE
Add support for AC (TCL/Kältebringer)

### ISSUE THREAD

**Issue by joystick666** [0x5e/homebridge-tuya-platform#151]
**Device info**
`"active_time": [1670854741](tel:1670854741),
"biz_type": 0,
"category": "kt",
"create_time": [1669892875](tel:1669892875),
"¡con": "smart/product_icon2/kt_1.png",
"id': "78004855c45bbed956f5",
"ip": "xxx",
"lat": "xxx",
"local_key": "xxx"
"lon": "xxx",
"model": ""
9
"name": "Klimaanlage Wohnzimmer",
"online": true,
"owner_id": "72997826",
"product_id": "hw50w7qvxluhslkk"
"product_name": "Air conditioner"
"status": [
"code"': "humidity_current",
"value": 0
{
"code"; "mode",
"value": "hot"
{
"code": "switch"
"value": true
{
'Code"': "temp_current",
"value": 23
"code": "temp_set",
"value": 230
{
"code": "temp_set_f",
"value": 61
], "isub": false,
"time zone": "+01:00"
"uid": "xxx", `

**Comment by joystick666** [comment]
MQTT log:
Request:
method = get
endpoint = https://openapi.tuyaeu.com
path = /v1.0/homes/72997826/devices
query = undefined
headers = {
  "t": "1671091101827",
  "client_id": "v7eq4cxmweag54hcgy5f",
  "nonce": "1f4cf116-a1e6-425e-b2a0-207e15d3f51d",
  "Signature-Headers": "client_id",
  "sign": "168AE84A9567BBE0EB6F7A020B5D3C612DC9FF30011C885DFCFD57F12BC52147",
  "sign_method": "HMAC-SHA256",
  "access_token": "0d74ddc5dded0875c4221f8bff086bdc",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.0.7"
}
body = null
[15.12.2022, 08:58:22] [TuyaPlatform] [TuyaOpenMQ] Connected
[15.12.2022, 08:58:22] [TuyaPlatform] [TuyaOpenAPI] Response:
path = /v1.0/homes/72997826/devices
data = {
  "result": [
    {
      "active_time": 1670854741,
      "biz_type": 0,
      "category": "kt",
      "create_time": 1669892875,
      "icon": "smart/product_icon2/kt_1.png",
      "id": "78004855c45bbed956f5",
      "ip": "95.88.11.147",
      "lat": "49.5645",
      "local_key": "f07dfd00d3719a6c",
      "lon": "8.0562",
      "model": "",
      "name": "Klimaanlage Wohnzimmer",
      "online": true,
      "owner_id": "72997826",
      "product_id": "hw50w7qvxluhslkk",
      "product_name": "Air conditioner",
      "status": [
        {
          "code": "switch",
          "value": true
        },
        {
          "code": "temp_set",
          "value": 230
        },
        {
          "code": "temp_current",
          "value": 22
        },
        {
          "code": "mode",
          "value": "hot"
        },
        {
          "code": "humidity_current",
          "value": 0
        },
        {
          "code": "temp_set_f",
          "value": 61
        }
      ],
      "sub": false,
      "time_zone": "+01:00",
      "uid": "eu1669901605949pwssf",
      "update_time": 1670923256,
      "uuid": "78004855c45bbed956f5"
    }
  ],
  "success": true,
  "t": 1671091102171,
  "tid": "3ec8ab517c4e11edbff6521277a1eee7"
}
[15.12.2022, 08:58:22] [TuyaPlatform] [TuyaOpenAPI] Request:
method = get
endpoint = https://openapi.tuyaeu.com
path = /v1.0/devices/78004855c45bbed956f5/specifications
query = undefined
headers = {
  "t": "1671091102183",
  "client_id": "v7eq4cxmweag54hcgy5f",
  "nonce": "07a40ba1-8ffe-4f3e-8f42-65872b258ee6",
  "Signature-Headers": "client_id",
  "sign": "AAD93D1C3AC7523506465FA155DEBCAC7156A240543A05A07B031FE9117B8909",
  "sign_method": "HMAC-SHA256",
  "access_token": "0d74ddc5dded0875c4221f8bff086bdc",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.0.7"
}
body = null
[15.12.2022, 08:58:22] [TuyaPlatform] [TuyaOpenAPI] Response:
path = /v1.0/devices/78004855c45bbed956f5/specifications
data = {
  "result": {
    "category": "kt",
    "functions": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":160,\"max\":880,\"scale\":1,\"step\":5}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"cold\",\"hot\",\"wet\",\"wind\",\"auto\"]}"
      },
      {
        "code": "temp_set_f",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":61,\"max\":88,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":160,\"max\":880,\"scale\":1,\"step\":5}"
      },
      {
        "code": "temp_current",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-20,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"cold\",\"hot\",\"wet\",\"wind\",\"auto\"]}"
      },
      {
        "code": "humidity_current",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_set_f",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":61,\"max\":88,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1671091102316,
  "tid": "3edfaf887c4e11edbff6521277a1eee7"
}

**Comment by 0x5e** [comment]
Please try the latest beta. Since homekit AirConditioner only have two mode hot and cold, I have to add dehumidifier and fan accessory to implement the dehumidification and wind mode.

**Comment by 0x5e** [comment]
And also @LazLong

**Comment by joystick666** [comment]
Thank you! I have it a short try, and it seem to work! Thank you. Will test more in the next days.
I get an additional Temperature reading that I don’t see in the app, is that the room temperature?

**Comment by 0x5e** [comment]
Yes that's the room temperature, is that value correct?

**Comment by joystick666** [comment]
It shows 25 degrees, and should be too high, as the room only is around 21,7 - 22, as I checked with my thermometer.

**Comment by LazLong** [comment]
Merry Christmas! That’s a nice present!Sent from my iPhoneOn 25 Dec 2022, at 07:01, gaosen ***@***.***> wrote:﻿
And also @LazLong

**Comment by 0x5e** [comment]
> It shows 25 degrees, and should be too high, as the room only is around 21,7 - 22, as I checked with my thermometer.

I just get it from `temp_current`, the document says "Current Temperature", does it changes with time, or with your target temperature?

**Comment by LazLong** [comment]
Unfortunately, my AC not at all happy - will experiment more tomorrow - no rush :)

[25/12/2022, 12:57:45] [TuyaPlatform] Restoring existing accessory from cache: PB-AC05
[25/12/2022, 12:57:45] [@0x5e/homebridge-tuya-platform] Characteristic 'Target Heater-Cooler State': characteristic value 0 is not contained in valid values array. See https://homebridge.io/w/JtMGR for more info.
[25/12/2022, 12:57:45] [@0x5e/homebridge-tuya-platform] Error: 
    at TargetHeaterCoolerState.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at TargetHeaterCoolerState.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2932:14)
    at TargetHeaterCoolerState.Characteristic.setProps (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2054:35)
    at AirConditionerAccessory.configureTargetState (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AirConditionerAccessory.ts:263:8)
    at AirConditionerAccessory.configureAirConditioner (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AirConditionerAccessory.ts:79:10)
    at AirConditionerAccessory.configureServices (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AirConditionerAccessory.ts:39:10)
    at Function.createAccessory (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AccessoryFactory.ts:158:15)
    at TuyaPlatform.addAccessory (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:340:40)
    at TuyaPlatform.initDevices (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:116:12)
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:71:7)
[25/12/2022, 12:57:45] [TuyaPlatform] [PB-AC05] Set props for CurrentTemperature: { minValue: -20, maxValue: 100, minStep: 1 }
[25/12/2022, 12:57:45] [TuyaPlatform] [PB-AC05] Set props for RotationSpeed: { minValue: 0, maxValue: 99, minStep: 33 }
[25/12/2022, 12:57:45] [TuyaPlatform] [PB-AC05] Set props for CoolingThresholdTemperature: { minValue: 16, maxValue: 86, minStep: 1 }
[25/12/2022, 12:57:45] [@0x5e/homebridge-tuya-platform] Characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 10 exceeded minimum of 16. See https://homebridge.io/w/JtMGR for more info.
[25/12/2022, 12:57:45] [@0x5e/homebridge-tuya-platform] Error: 
    at CoolingThresholdTemperature.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at CoolingThresholdTemperature.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2923:14)
    at CoolingThresholdTemperature.Characteristic.setProps (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2054:35)
    at AirConditionerAccessory.configureCoolingThreshouldTemp (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AirConditionerAccessory.ts:302:8)
    at AirConditionerAccessory.configureAirConditioner (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AirConditionerAccessory.ts:86:10)
    at AirConditionerAccessory.configureServices (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AirConditionerAccessory.ts:39:10)
    at Function.createAccessory (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AccessoryFactory.ts:158:15)
    at TuyaPlatform.addAccessory (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:340:40)
    at TuyaPlatform.initDevices (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:116:12)
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:71:7)
[25/12/2022, 12:57:45] [TuyaPlatform] [PB-AC05] Set props for HeatingThresholdTemperature: { minValue: 16, maxValue: 86, minStep: 1 }
[25/12/2022, 12:57:45] [@0x5e/homebridge-tuya-platform] Characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 16. See https://homebridge.io/w/JtMGR for more info.
[25/12/2022, 12:57:45] [@0x5e/homebridge-tuya-platform] Error: 
    at HeatingThresholdTemperature.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at HeatingThresholdTemperature.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2923:14)
    at HeatingThresholdTemperature.Characteristic.setProps (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2054:35)
    at AirConditionerAccessory.configureHeatingThreshouldTemp (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AirConditionerAccessory.ts:341:8)
    at AirConditionerAccessory.configureAirConditioner (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AirConditionerAccessory.ts:87:10)
    at AirConditionerAccessory.configureServices (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AirConditionerAccessory.ts:39:10)
    at Function.createAccessory (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AccessoryFactory.ts:158:15)
    at TuyaPlatform.addAccessory (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:340:40)
    at TuyaPlatform.initDevices (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:116:12)
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:71:7)
[25/12/2022, 12:57:45] [@0x5e/homebridge-tuya-platform] Characteristic 'Target Humidifier-Dehumidifier State': characteristic value 0 is not contained in valid values array. See https://homebridge.io/w/JtMGR for more info.
[25/12/2022, 12:57:45] [@0x5e/homebridge-tuya-platform] Error: 
    at TargetHumidifierDehumidifierState.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at TargetHumidifierDehumidifierState.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2932:14)
    at TargetHumidifierDehumidifierState.Characteristic.setProps (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2054:35)
    at AirConditionerAccessory.configureDehumidifier (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AirConditionerAccessory.ts:130:8)
    at AirConditionerAccessory.configureServices (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AirConditionerAccessory.ts:40:10)
    at Function.createAccessory (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AccessoryFactory.ts:158:15)
    at TuyaPlatform.addAccessory (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:340:40)
    at TuyaPlatform.initDevices (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:116:12)
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:71:7)
[25/12/2022, 12:57:45] [TuyaPlatform] [PB-AC05] Set props for RotationSpeed: { minValue: 0, maxValue: 99, minStep: 33 }
[25/12/2022, 12:57:45] [TuyaPlatform] [PB-AC05] Set props for RotationSpeed: { minValue: 0, maxValue: 99, minStep: 33 }
[25/12/2022, 12:57:45] [TuyaPlatform] [PB-AC05] Update value 0 => 22 for service = '000000BC-0000-1000-8000-0026BB765291', subtype = undefined, characteristic = '00000011-0000-1000-8000-0026BB765291'
[25/12/2022, 12:57:45] [TuyaPlatform] [PB-AC05] Update value 0 => 33 for service = '000000BC-0000-1000-8000-0026BB765291', subtype = undefined, characteristic = '00000029-0000-1000-8000-0026BB765291'
[25/12/2022, 12:57:45] [TuyaPlatform] [PB-AC05] Update value 16 => 20 for service = '000000BC-0000-1000-8000-0026BB765291', subtype = undefined, characteristic = '0000000D-0000-1000-8000-0026BB765291'
[25/12/2022, 12:57:45] [TuyaPlatform] [PB-AC05] Update value 16 => 20 for service = '000000BC-0000-1000-8000-0026BB765291', subtype = undefined, characteristic = '00000012-0000-1000-8000-0026BB765291'
[25/12/2022, 12:57:45] [TuyaPlatform] [PB-AC05] Update value 0 => 3 for service = '000000BD-0000-1000-8000-0026BB765291', subtype = undefined, characteristic = '000000B3-0000-1000-8000-0026BB765291'
[25/12/2022, 12:57:45] [TuyaPlatform] [PB-AC05] Update value 0 => 33 for service = '000000BD-0000-1000-8000-0026BB765291', subtype = undefined, characteristic = '00000029-0000-1000-8000-0026BB765291'
[25/12/2022, 12:57:45] [TuyaPlatform] [PB-AC05] Update value 0 => 33 for service = '000000B7-0000-1000-8000-0026BB765291', subtype = undefined, characteristic = '00000029-0000-1000-8000-0026BB765291'

**Comment by 0x5e** [comment]
@LazLong Thanks for the information, there's 4 errors:
1. 'Target Heater-Cooler State': characteristic value 0 is not contained in valid values array.
2. 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 10 exceeded minimum of 16.
3. 'Heating Threshold Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 16.
4. 'Target Humidifier-Dehumidifier State': characteristic value 0 is not contained in valid values array.

1 and 4 can be ignored if the device can be functional, I will try to silence these logs.
2 and 3 I checked your device's schema, seems the value is stored with `realTemperature*2`:
```js
{
  "code": "temp_set",
  "mode": "rw",
  "type": "Integer",
  "property": {
    "min": 16,
    "unit": "℃",
    "scale": 0,
    "max": 86,
    "step": 1
  }
}
```

I think no AC are able to set target temperature of 86 degree, the range 16-86 I guess is 8-43. Can you confirm the device's actual setting range in each modes? If it's real what I have said, you can manually set device config: https://github.com/0x5e/homebridge-tuya-platform/blob/develop_1.7.0/ADVANCED_OPTIONS.md#adjust-integer-dp-ranges

**Comment by joystick666** [comment]
Did not change at all since the last 2 hrs, maybe this is not supported for all ACs, because like I said: 
it’s not available in the Tuya or Smartlife app

**Comment by 0x5e** [comment]
> Did not change at all since the last 2 hrs, maybe this is not supported for all ACs, because like I said: it’s not available in the Tuya or Smartlife app

Fine, maybe it's a constant fake value, but the plugin are not able to know wether it's real or fake..
