### ISSUE TITLE
Lights without "work_mode" crashes

### ISSUE THREAD

**Issue by VigoKrumins** [0x5e/homebridge-tuya-platform#186]
After the update to the "src/accessory/characteristic/Light.ts" Lights that doesn't have "work_mode" crashes the Homebridge. Possible workaround for now is to "hide" the accessory.

```
[29/12/2022, 17:30:43] TypeError: Cannot read properties of undefined (reading 'range')
    at getLightType (/usr/local/lib/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/characteristic/Light.ts:34:70)
    at configureLight (/usr/local/lib/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/characteristic/Light.ts:290:21)
    at LightAccessory.configureServices (/usr/local/lib/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/LightAccessory.ts:28:19)
    at Function.createAccessory (/usr/local/lib/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AccessoryFactory.ts:162:15)
    at TuyaPlatform.addAccessory (/usr/local/lib/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:357:40)
    at TuyaPlatform.initDevices (/usr/local/lib/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:116:12)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:71:7)```

**Comment by 0x5e** [comment]
fixed in beta.19, please confirm.

**Comment by VigoKrumins** [comment]
It works like a charm! Thank you! Fixed. :)
