### ISSUE TITLE
Child Process Crashing

### ISSUE THREAD

**Issue by xtinct101** [0x5e/homebridge-tuya-platform#210]
- [x ] I've read the [Readme - FAQ](https://github.com/0x5e/homebridge-tuya-platform#faq) and [Readme - Troubleshooting](https://github.com/0x5e/homebridge-tuya-platform#troubleshooting) section.

**Describe the bug**
Upgrading to 1.7 beta 22 causes the bridge to crash on a loop.

**Expected behavior**
Load and expose all lights. Version 1.6 seems to load correctly.

**Screenshots**
<img width="903" alt="Screenshot 2023-01-14 073730" src="https://user-images.githubusercontent.com/89475753/212480135-99774406-c6be-45f9-a1d8-d2e22069cc23.png">

**Device info**

**Comment by 0x5e** [comment]
the screenshot is incomplete, what's the light type of the device?

**Comment by 0x5e** [comment]
Same with #181 , I need some detail info to locate this issue, please refer to faq and post device info json, thanks.

**Comment by xtinct101** [comment]
Hi 0x5e,
First thanks for the plugin its awesome.

Here is the device list and the complete log:

Tuya Device List: https://pastebin.com/4j33RL9C

```[1/14/2023, 10:50:46 AM] Homebridge v1.6.0 (HAP v0.11.0) (TuyaPlatform) is running on port 41722.
[1/14/2023, 10:50:46 AM] [TuyaPlatform] Start MQTT connection.
[1/14/2023, 10:50:46 AM] [TuyaPlatform] Fetching home list.
[1/14/2023, 10:50:46 AM] [TuyaPlatform] Got home_id=22519923, name=10 Magnolia
[1/14/2023, 10:50:46 AM] [TuyaPlatform] Fetching device list.
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Fetching scene list.
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Got 39 device(s) and scene(s).
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Device list saved at /var/lib/homebridge/persist/TuyaDeviceList.az1599432911755UihBA.json
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache:  Backyard String Lights 1
[1/14/2023, 10:50:54 AM] [TuyaPlatform] [ Backyard String Lights 1] Light type: C
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache:  Backyard String Lights 2
[1/14/2023, 10:50:54 AM] [TuyaPlatform] [ Backyard String Lights 2] Light type: C
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Garage Side Door Light
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Guest Bedroom Light
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Master Bathroom Can Lights
[1/14/2023, 10:50:54 AM] [TuyaPlatform] [Master Bathroom Can Lights] Light type: C
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Master Bathroom Pendant Lights
[1/14/2023, 10:50:54 AM] [TuyaPlatform] [Master Bathroom Pendant Lights] Light type: C
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Zoe’s Room Light
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Master Bedroom Ceiling Fan
[1/14/2023, 10:50:54 AM] [TuyaPlatform] [Master Bedroom Ceiling Fan] Light type: C
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Zoe’s Room Ceiling Fan
[1/14/2023, 10:50:54 AM] [TuyaPlatform] [Zoe’s Room Ceiling Fan] Light type: C
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Kids Bathroom Pendant Lights
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Kids Bathroom Shower Fan
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Kids Bathroom Shower Light
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Maia’s Room Light
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Maia’s Room Ceiling Fan
[1/14/2023, 10:50:54 AM] [TuyaPlatform] [Maia’s Room Ceiling Fan] Light type: C
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Jade’s Wall Light
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Jade’s Room Can Lights
[1/14/2023, 10:50:54 AM] [TuyaPlatform] [Jade’s Room Can Lights] Light type: C
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Jade’s Room Fan
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Stairs Light
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Front Porch Light
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Hallway Light - Downstairs
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Family Room Lights
[1/14/2023, 10:50:54 AM] [TuyaPlatform] [Family Room Lights] Light type: C
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Kitchen Under-Counter Lights
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Garage Door Light
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Garage Light
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Guest Bathroom Can Lights
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Guest Bathroom Pendant Lights 
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Guest Bathroom Fan
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Backyard Vergola Light
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Fountains 
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Garage Fan
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Router
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Dining Room Light
[1/14/2023, 10:50:54 AM] [TuyaPlatform] [Dining Room Light] Light type: C
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Landscape Lights 
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Garage Fan Plug
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Spa Stairs Lights
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Kitchen Pendant Lights
[1/14/2023, 10:50:54 AM] [TuyaPlatform] [Kitchen Pendant Lights] Light type: C
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Guest Bedroom Ceiling Fan 
[1/14/2023, 10:50:54 AM] [TuyaPlatform] [Guest Bedroom Ceiling Fan ] Light type: C
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Kitchen Can Lights
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Restoring existing accessory from cache: Front Room Light
TypeError: Cannot destructure property 'max' of 'colorSchema.property.v' as it is undefined.
    at /homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/characteristic/Light.ts:116:17
    at LightAccessory.updateAllValues (/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/BaseAccessory.ts:112:46)
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Child bridge process ended
[1/14/2023, 10:50:54 AM] [TuyaPlatform] Process Ended. Code: 1, Signal: null```

Let me know if I can supply you with anything else.

**Comment by 0x5e** [comment]
thanks for the feedback, I will submit a fix version later.

**Comment by 0x5e** [comment]
I'm going to closing this. If problem still exist, please let me know.
