### ISSUE TITLE
IR Devices error out as the limit is 100 services per accessory.

### ISSUE THREAD

**Issue by bimusiek** [0x5e/homebridge-tuya-platform#238]
- [x] I've read the [Readme - FAQ](https://github.com/0x5e/homebridge-tuya-platform#faq) and [Readme - Troubleshooting](https://github.com/0x5e/homebridge-tuya-platform#troubleshooting) section.

**Describe the bug**

```
[21/02/2023, 14:40:43] Error: Cannot add more than 100 services to a single accessory!
    at Accessory.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:480:13)
    at PlatformAccessory.addService (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at IRGenericAccessory.configureSwitch (/usr/lib/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/IRGenericAccessory.ts:19:25)
    at IRGenericAccessory.configureServices (/usr/lib/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/IRGenericAccessory.ts:13:12)
    at Function.createAccessory (/usr/lib/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AccessoryFactory.ts:206:13)
    at TuyaPlatform.addAccessory (/usr/lib/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:356:40)
    at TuyaPlatform.initDevices (/usr/lib/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:128:12)
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:71:7)
```

**Expected behavior**
Should split IR controls in 100 chunks I think.

**Screenshots**

**Device info**
If the issue is related to a device, please provide the device info list and debug logs.

**Comment by brunohenriquy** [comment]
I am also having this same issue, I don't have more than 100 devices, I have about 30. What is considered an accessory?
Also could you merge the PR @bimusiek opened? Does it fix the issue?

**Comment by brunohenriquy** [comment]
I just tryied v1.7.0-beta.43, because I saw there was a commit that could maybe fix it https://github.com/0x5e/homebridge-tuya-platform/commit/ec6cf69d4babcc62cab1f9dc2510808ed8b49041, but I am still geting the same error:

```
Error: Cannot add more than 100 services to a single accessory!
    at Accessory.addService (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:564:13)
    at PlatformAccessory.addService (/homebridge/node_modules/homebridge/src/platformAccessory.ts:98:41)
    at IRGenericAccessory.configureSwitch (/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/IRGenericAccessory.ts:16:25)
    at IRGenericAccessory.configureServices (/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/IRGenericAccessory.ts:10:12)
    at Function.createAccessory (/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AccessoryFactory.ts:224:13)
    at TuyaPlatform.addAccessory (/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:444:40)
    at TuyaPlatform.initDevices (/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:195:12)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:128:7)

**Comment by 0x5e** [comment]
Please confirm if it's working on beta.44, not sure if the calculation was wrong :)

**Comment by brunohenriquy** [comment]
Oh that make sense now! It's working on beta.44 and the log is very well explained xD.
```
[Tuya] [TV] Skipping 17 keys for TV, as we reached the limit of HomeKit (100 services per accessory)
```

Thanks!!

**Comment by brunohenriquy** [comment]
Although it is not showing the error anymore, here it shows as not supported, is that not supported yet @0x5e?
![IMG_0048](https://user-images.githubusercontent.com/8320519/236662043-5e4bf5d0-51b0-4b3b-af7b-36eb7fb08e34.jpg)
![IMG_0049](https://user-images.githubusercontent.com/8320519/236662056-c95101c9-b472-4db7-abfe-813a34813fae.PNG)

**Comment by 0x5e** [comment]
@brunohenriquy try clean cache, if still not working please post debug logs

**Comment by bimusiek** [comment]
@0x5e The issue is we skip re-creating/creating new devices but in case those were added before, the code should simply iterate over those ignored ones and remove it if it exists. 

Otherwise, you have to manually click through tens of cached accessories to remove those from cache.

**Comment by 0x5e** [comment]
@bimusiek apologize for my laziness at this point, I understand a good developer should handle cache properly during the software update.

In the beta version, free open-source program, lack time to maintain the code, I may not take good care about this, in the release version I will.

**Comment by brunohenriquy** [comment]
@0x5e cleanning cache worked, thanks. But there are so many items that I can't pass "Power Off" labels and get to the real buttons in iOS, it doesn't create a scrol like in Home on MacOS. But I thing this is a Home iOS App problem. Or is there a way to remove those labels adjusting some code in the plugin?
---
Home in MacOS
<img width="507" alt="Screenshot 2023-05-08 at 13 18 50" src="https://user-images.githubusercontent.com/8320519/236876403-25a583b9-ca96-4545-acdd-cb66d1321f4a.png">

**Comment by 0x5e** [comment]
> @0x5e cleanning cache worked, thanks. But there are so many items that I can't pass "Power Off" labels and get to the real buttons in iOS, it doesn't create a scrol like in Home on MacOS. But I thing this is a Home iOS App problem. Or is there a way to remove those labels adjusting some code in the plugin?
> 
> Home in MacOS <img alt="Screenshot 2023-05-08 at 13 18 50" width="507" src="https://user-images.githubusercontent.com/8320519/236876403-25a583b9-ca96-4545-acdd-cb66d1321f4a.png">

Not yet. After #285 merged, [Television](https://developers.homebridge.io/#/service/Television) may be possible to use. I will investigate time to try it, it will be better than hundreds of switches.

**Comment by brunohenriquy** [comment]
Gotcha, Thanks @0x5e
