### ISSUE TITLE
Error installation 1.7.0-Beta33

### ISSUE THREAD

**Issue by metalnodeug** [0x5e/homebridge-tuya-platform#263]
### Prerequisite

- [X] Yes

### Version

1.7.0-Beta..

### Device Control Mode

Standard Instruction

### Logs

```shell
0 verbose cli /opt/homebridge/bin/node /opt/homebridge/bin/npm
1 info using npm@8.19.2
2 info using node@v18.12.1
3 timing npm:load:whichnode Completed in 7ms
4 timing config:load:defaults Completed in 151ms
5 timing config:load:file:/opt/homebridge/lib/node_modules/npm/npmrc Completed in 125ms
6 timing config:load:builtin Completed in 168ms
7 timing config:load:cli Completed in 405ms
8 timing config:load:env Completed in 30ms
9 timing config:load:file:/var/lib/homebridge/.npmrc Completed in 52ms
10 timing config:load:project Completed in 229ms
11 timing config:load:file:/home/pi/.npmrc Completed in 3ms
12 timing config:load:user Completed in 12ms
13 timing config:load:file:/opt/homebridge/etc/npmrc Completed in 4ms
14 timing config:load:global Completed in 8ms
15 timing config:load:validate Completed in 27ms
16 timing config:load:credentials Completed in 39ms
17 timing config:load:setEnvs Completed in 45ms
18 timing config:load Completed in 1153ms
19 timing npm:load:configload Completed in 1161ms
20 timing npm:load:mkdirpcache Completed in 37ms
21 timing npm:load:mkdirplogs Completed in 11ms
22 verbose title npm install @0x5e/homebridge-tuya-platform@1.7.0-beta.33
23 verbose argv "install" "--save" "@0x5e/homebridge-tuya-platform@1.7.0-beta.33"
24 timing npm:load:setTitle Completed in 52ms
25 timing config:load:flatten Completed in 150ms
26 timing npm:load:display Completed in 244ms
27 verbose logfile logs-max:10 dir:/home/pi/.npm/_logs
28 verbose logfile /home/pi/.npm/_logs/2023-03-16T20_21_40_612Z-debug-0.log
29 timing npm:load:logFile Completed in 230ms
30 timing npm:load:timers Completed in 3ms
31 timing npm:load:configScope Completed in 2ms
32 timing npm:load Completed in 1787ms
33 timing arborist:ctor Completed in 40ms
34 silly logfile done cleaning log files
35 timing arborist:ctor Completed in 17ms
36 timing arborist:ctor Completed in 3ms
37 timing arborist:ctor Completed in 3ms
38 timing idealTree:init Completed in 16248ms
39 timing idealTree:userRequests Completed in 91ms
40 silly idealTree buildDeps
41 silly fetch manifest @0x5e/homebridge-tuya-platform@1.7.0-beta.33
42 http fetch GET 200 https://registry.npmjs.org/@0x5e%2fhomebridge-tuya-platform 4589ms (cache revalidated)
43 silly placeDep ROOT @0x5e/homebridge-tuya-platform@1.7.0-beta.33 REPLACE for:  want: 1.7.0-beta.33
44 silly fetch manifest @homebridge/camera-utils@^2.2.0
45 silly fetch manifest lodash.isequal@^4.5.0
46 http fetch GET 200 https://registry.npmjs.org/lodash.isequal 987ms (cache revalidated)
47 http fetch GET 200 https://registry.npmjs.org/@homebridge%2fcamera-utils 1688ms (cache revalidated)
48 timing idealTree:#root Completed in 8537ms
49 silly placeDep node_modules/@0x5e/homebridge-tuya-platform @homebridge/camera-utils@2.2.0 OK for: @0x5e/homebridge-tuya-platform@1.7.0-beta.33 want: ^2.2.0
50 silly placeDep node_modules/@0x5e/homebridge-tuya-platform lodash.isequal@4.5.0 OK for: @0x5e/homebridge-tuya-platform@1.7.0-beta.33 want: ^4.5.0
51 silly fetch manifest execa@^5.1.1
52 silly fetch manifest ffmpeg-for-homebridge@^0.1.4
53 silly fetch manifest pick-port@^1.0.1
54 silly fetch manifest rxjs@^7.5.6
55 silly fetch manifest systeminformation@^5.12.1
56 http fetch GET 200 https://registry.npmjs.org/rxjs 2199ms (cache revalidated)
57 http fetch GET 200 https://registry.npmjs.org/execa 2931ms (cache revalidated)
58 http fetch GET 200 https://registry.npmjs.org/systeminformation 3167ms (cache revalidated)
59 http fetch GET 200 https://registry.npmjs.org/ffmpeg-for-homebridge 3525ms (cache revalidated)
60 http fetch GET 200 https://registry.npmjs.org/pick-port 3783ms (cache revalidated)
61 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform Completed in 4023ms
62 silly placeDep node_modules/@0x5e/homebridge-tuya-platform execa@5.1.1 OK for: @homebridge/camera-utils@2.2.0 want: ^5.1.1
63 silly placeDep node_modules/@0x5e/homebridge-tuya-platform ffmpeg-for-homebridge@0.1.4 OK for: @homebridge/camera-utils@2.2.0 want: ^0.1.4
64 silly placeDep node_modules/@0x5e/homebridge-tuya-platform pick-port@1.0.1 OK for: @homebridge/camera-utils@2.2.0 want: ^1.0.1
65 silly placeDep node_modules/@0x5e/homebridge-tuya-platform rxjs@7.8.0 OK for: @homebridge/camera-utils@2.2.0 want: ^7.5.6
66 silly placeDep node_modules/@0x5e/homebridge-tuya-platform systeminformation@5.17.12 OK for: @homebridge/camera-utils@2.2.0 want: ^5.12.1
67 silly fetch manifest cross-spawn@^7.0.3
68 silly fetch manifest get-stream@^6.0.0
69 silly fetch manifest human-signals@^2.1.0
70 silly fetch manifest is-stream@^2.0.0
71 silly fetch manifest merge-stream@^2.0.0
72 silly fetch manifest npm-run-path@^4.0.1
73 silly fetch manifest onetime@^5.1.2
74 silly fetch manifest signal-exit@^3.0.3
75 silly fetch manifest strip-final-newline@^2.0.0
76 silly fetch manifest detect-libc@^2.0.1
77 silly fetch manifest dotenv@^16.0.1
78 silly fetch manifest simple-get@^4.0.1
79 silly fetch manifest tar@^6.1.11
80 silly fetch manifest tslib@^2.1.0
81 http fetch GET 200 https://registry.npmjs.org/cross-spawn 5054ms (cache revalidated)
82 http fetch GET 200 https://registry.npmjs.org/human-signals 5066ms (cache revalidated)
83 http fetch GET 200 https://registry.npmjs.org/is-stream 5098ms (cache revalidated)
84 http fetch GET 200 https://registry.npmjs.org/merge-stream 5152ms (cache revalidated)
85 http fetch GET 200 https://registry.npmjs.org/get-stream 5249ms (cache revalidated)
86 http fetch GET 200 https://registry.npmjs.org/npm-run-path 5390ms (cache revalidated)
87 http fetch GET 200 https://registry.npmjs.org/onetime 5405ms (cache revalidated)
88 http fetch GET 200 https://registry.npmjs.org/signal-exit 5440ms (cache revalidated)
89 http fetch GET 200 https://registry.npmjs.org/strip-final-newline 5461ms (cache revalidated)
90 http fetch GET 200 https://registry.npmjs.org/detect-libc 5470ms (cache revalidated)
91 http fetch GET 200 https://registry.npmjs.org/dotenv 5481ms (cache revalidated)
92 http fetch GET 200 https://registry.npmjs.org/simple-get 5516ms (cache revalidated)
93 http fetch GET 200 https://registry.npmjs.org/tar 5565ms (cache revalidated)
94 http fetch GET 200 https://registry.npmjs.org/tslib 5623ms (cache revalidated)
95 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/@homebridge/camera-utils Completed in 6288ms
96 silly placeDep node_modules/@0x5e/homebridge-tuya-platform cross-spawn@7.0.3 OK for: execa@5.1.1 want: ^7.0.3
97 silly placeDep node_modules/@0x5e/homebridge-tuya-platform get-stream@6.0.1 OK for: execa@5.1.1 want: ^6.0.0
98 silly placeDep node_modules/@0x5e/homebridge-tuya-platform human-signals@2.1.0 OK for: execa@5.1.1 want: ^2.1.0
99 silly placeDep node_modules/@0x5e/homebridge-tuya-platform is-stream@2.0.1 OK for: execa@5.1.1 want: ^2.0.0
100 silly placeDep node_modules/@0x5e/homebridge-tuya-platform merge-stream@2.0.0 OK for: execa@5.1.1 want: ^2.0.0
101 silly placeDep node_modules/@0x5e/homebridge-tuya-platform npm-run-path@4.0.1 OK for: execa@5.1.1 want: ^4.0.1
102 silly placeDep node_modules/@0x5e/homebridge-tuya-platform onetime@5.1.2 OK for: execa@5.1.1 want: ^5.1.2
103 silly placeDep node_modules/@0x5e/homebridge-tuya-platform signal-exit@3.0.7 OK for: execa@5.1.1 want: ^3.0.3
104 silly placeDep node_modules/@0x5e/homebridge-tuya-platform strip-final-newline@2.0.0 OK for: execa@5.1.1 want: ^2.0.0
105 silly fetch manifest path-key@^3.1.0
106 silly fetch manifest shebang-command@^2.0.0
107 silly fetch manifest which@^2.0.1
108 silly fetch manifest path-key@^3.0.0
109 silly fetch manifest mimic-fn@^2.1.0
110 http fetch GET 200 https://registry.npmjs.org/path-key 1721ms (cache revalidated)
111 http fetch GET 200 https://registry.npmjs.org/shebang-command 1718ms (cache revalidated)
112 http fetch GET 200 https://registry.npmjs.org/path-key 1640ms (cache revalidated)
113 http fetch GET 200 https://registry.npmjs.org/mimic-fn 1618ms (cache revalidated)
114 http fetch GET 200 https://registry.npmjs.org/which 3572ms (cache revalidated)
115 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/execa Completed in 4488ms
116 silly placeDep node_modules/@0x5e/homebridge-tuya-platform path-key@3.1.1 OK for: cross-spawn@7.0.3 want: ^3.1.0
117 silly placeDep node_modules/@0x5e/homebridge-tuya-platform shebang-command@2.0.0 OK for: cross-spawn@7.0.3 want: ^2.0.0
118 silly placeDep node_modules/@0x5e/homebridge-tuya-platform which@2.0.2 OK for: cross-spawn@7.0.3 want: ^2.0.1
119 silly fetch manifest shebang-regex@^3.0.0
120 silly fetch manifest isexe@^2.0.0
121 http fetch GET 200 https://registry.npmjs.org/shebang-regex 969ms (cache revalidated)
122 http fetch GET 200 https://registry.npmjs.org/isexe 950ms (cache revalidated)
123 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/cross-spawn Completed in 1254ms
124 silly placeDep node_modules/@0x5e/homebridge-tuya-platform detect-libc@2.0.1 OK for: ffmpeg-for-homebridge@0.1.4 want: ^2.0.1
125 silly placeDep node_modules/@0x5e/homebridge-tuya-platform dotenv@16.0.3 OK for: ffmpeg-for-homebridge@0.1.4 want: ^16.0.1
126 silly placeDep node_modules/@0x5e/homebridge-tuya-platform simple-get@4.0.1 OK for: ffmpeg-for-homebridge@0.1.4 want: ^4.0.1
127 silly placeDep node_modules/@0x5e/homebridge-tuya-platform tar@6.1.13 OK for: ffmpeg-for-homebridge@0.1.4 want: ^6.1.11
128 silly fetch manifest decompress-response@^6.0.0
129 silly fetch manifest simple-concat@^1.0.0
130 silly fetch manifest chownr@^2.0.0
131 silly fetch manifest fs-minipass@^2.0.0
132 silly fetch manifest minipass@^4.0.0
133 silly fetch manifest minizlib@^2.1.1
134 silly fetch manifest mkdirp@^1.0.3
135 http fetch GET 200 https://registry.npmjs.org/decompress-response 2905ms (cache revalidated)
136 http fetch GET 200 https://registry.npmjs.org/simple-concat 2959ms (cache revalidated)
137 http fetch GET 200 https://registry.npmjs.org/chownr 2961ms (cache revalidated)
138 http fetch GET 200 https://registry.npmjs.org/fs-minipass 2958ms (cache revalidated)
139 http fetch GET 200 https://registry.npmjs.org/minipass 2989ms (cache revalidated)
140 http fetch GET 200 https://registry.npmjs.org/minizlib 2999ms (cache revalidated)
141 http fetch GET 200 https://registry.npmjs.org/mkdirp 2994ms (cache revalidated)
142 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/ffmpeg-for-homebridge Completed in 3691ms
143 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/detect-libc Completed in 2ms
144 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/dotenv Completed in 1ms
145 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/get-stream Completed in 1ms
146 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/human-signals Completed in 3ms
147 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/is-stream Completed in 1ms
148 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/lodash.isequal Completed in 1ms
149 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/merge-stream Completed in 1ms
150 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/npm-run-path Completed in 1ms
151 silly placeDep node_modules/@0x5e/homebridge-tuya-platform mimic-fn@2.1.0 OK for: onetime@5.1.2 want: ^2.1.0
152 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/onetime Completed in 67ms
153 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/mimic-fn Completed in 2ms
154 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/path-key Completed in 1ms
155 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/pick-port Completed in 1ms
156 silly placeDep node_modules/@0x5e/homebridge-tuya-platform tslib@2.5.0 OK for: rxjs@7.8.0 want: ^2.1.0
157 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/rxjs Completed in 119ms
158 silly placeDep node_modules/@0x5e/homebridge-tuya-platform shebang-regex@3.0.0 OK for: shebang-command@2.0.0 want: ^3.0.0
159 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/shebang-command Completed in 87ms
160 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/shebang-regex Completed in 3ms
161 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/signal-exit Completed in 1ms
162 silly placeDep node_modules/@0x5e/homebridge-tuya-platform decompress-response@6.0.0 OK for: simple-get@4.0.1 want: ^6.0.0
163 silly placeDep node_modules/@0x5e/homebridge-tuya-platform simple-concat@1.0.1 OK for: simple-get@4.0.1 want: ^1.0.0
164 silly fetch manifest mimic-response@^3.1.0
165 http fetch GET 200 https://registry.npmjs.org/mimic-response 1151ms (cache revalidated)
166 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/simple-get Completed in 1491ms
167 silly placeDep node_modules/@0x5e/homebridge-tuya-platform mimic-response@3.1.0 OK for: decompress-response@6.0.0 want: ^3.1.0
168 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/decompress-response Completed in 52ms
169 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/mimic-response Completed in 0ms
170 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/simple-concat Completed in 1ms
171 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/strip-final-newline Completed in 1ms
172 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/systeminformation Completed in 1ms
173 silly placeDep node_modules/@0x5e/homebridge-tuya-platform chownr@2.0.0 OK for: tar@6.1.13 want: ^2.0.0
174 silly placeDep node_modules/@0x5e/homebridge-tuya-platform fs-minipass@2.1.0 OK for: tar@6.1.13 want: ^2.0.0
175 silly placeDep node_modules/@0x5e/homebridge-tuya-platform minipass@4.2.5 OK for: tar@6.1.13 want: ^4.0.0
176 silly placeDep node_modules/@0x5e/homebridge-tuya-platform minizlib@2.1.2 OK for: tar@6.1.13 want: ^2.1.1
177 silly placeDep node_modules/@0x5e/homebridge-tuya-platform mkdirp@1.0.4 OK for: tar@6.1.13 want: ^1.0.3
178 silly fetch manifest minipass@^3.0.0
179 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/tar Completed in 513ms
180 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/chownr Completed in 2ms
181 silly placeDep node_modules/@0x5e/homebridge-tuya-platform/node_modules/fs-minipass minipass@3.3.6 OK for: fs-minipass@2.1.0 want: ^3.0.0
182 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/fs-minipass Completed in 177ms
183 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/minipass Completed in 2ms
184 silly placeDep node_modules/@0x5e/homebridge-tuya-platform/node_modules/minizlib minipass@3.3.6 OK for: minizlib@2.1.2 want: ^3.0.0
185 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/minizlib Completed in 137ms
186 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/mkdirp Completed in 5ms
187 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/tslib Completed in 2ms
188 silly placeDep node_modules/@0x5e/homebridge-tuya-platform isexe@2.0.0 OK for: which@2.0.2 want: ^2.0.0
189 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/which Completed in 111ms
190 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/isexe Completed in 2ms
191 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/fs-minipass/node_modules/minipass Completed in 3ms
192 timing idealTree:node_modules/@0x5e/homebridge-tuya-platform/node_modules/minizlib/node_modules/minipass Completed in 2ms
193 timing idealTree:buildDeps Completed in 31439ms
194 timing idealTree:fixDepFlags Completed in 523ms
195 timing idealTree Completed in 48556ms
196 timing reify:loadTrees Completed in 48595ms
197 timing reify:diffTrees Completed in 327ms
198 silly reify mark retired [ '/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform' ]
199 silly reify moves {
199 silly reify   '/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform': '/var/lib/homebridge/node_modules/@0x5e/.homebridge-tuya-platform-1Fbo13lg'
199 silly reify }
200 timing reify:retireShallow Completed in 348ms
201 timing reify:createSparse Completed in 983ms
202 timing reify:loadBundles Completed in 1ms
203 http fetch GET 200 https://registry.npmjs.org/@0x5e/homebridge-tuya-platform/-/homebridge-tuya-platform-1.7.0-beta.33.tgz 19010ms (cache revalidated)
204 http fetch GET 200 https://registry.npmjs.org/tar/-/tar-6.1.13.tgz 17917ms (cache revalidated)
205 http fetch GET 200 https://registry.npmjs.org/simple-get/-/simple-get-4.0.1.tgz 19051ms (cache revalidated)
206 http fetch GET 200 https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz 20467ms (cache revalidated)
207 http fetch GET 200 https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz 20476ms (cache revalidated)
208 http fetch GET 200 https://registry.npmjs.org/minizlib/-/minizlib-2.1.2.tgz 20551ms (cache revalidated)
209 http fetch GET 200 https://registry.npmjs.org/minipass/-/minipass-3.3.6.tgz 20617ms (cache revalidated)
210 http fetch GET 200 https://registry.npmjs.org/minipass/-/minipass-4.2.5.tgz 20695ms (cache revalidated)
211 http fetch GET 200 https://registry.npmjs.org/fs-minipass/-/fs-minipass-2.1.0.tgz 20783ms (cache revalidated)
212 http fetch GET 200 https://registry.npmjs.org/minipass/-/minipass-3.3.6.tgz 20894ms (cache revalidated)
213 http fetch GET 200 https://registry.npmjs.org/chownr/-/chownr-2.0.0.tgz 20985ms (cache revalidated)
214 http fetch GET 200 https://registry.npmjs.org/mimic-response/-/mimic-response-3.1.0.tgz 20965ms (cache revalidated)
215 http fetch GET 200 https://registry.npmjs.org/simple-concat/-/simple-concat-1.0.1.tgz 20909ms (cache revalidated)
216 http fetch GET 200 https://registry.npmjs.org/decompress-response/-/decompress-response-6.0.0.tgz 20891ms (cache revalidated)
217 http fetch GET 200 https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz 20887ms (cache revalidated)
218 http fetch GET 200 https://registry.npmjs.org/tslib/-/tslib-2.5.0.tgz 20903ms (cache revalidated)
219 http fetch GET 200 https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz 20902ms (cache revalidated)
220 http fetch GET 200 https://registry.npmjs.org/dotenv/-/dotenv-16.0.3.tgz 20996ms (cache revalidated)
221 http fetch GET 200 https://registry.npmjs.org/detect-libc/-/detect-libc-2.0.1.tgz 20957ms (cache revalidated)
222 http fetch GET 200 https://registry.npmjs.org/which/-/which-2.0.2.tgz 20995ms (cache revalidated)
223 http fetch GET 200 https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz 20999ms (cache revalidated)
224 http fetch GET 200 https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz 21022ms (cache revalidated)
225 http fetch GET 200 https://registry.npmjs.org/strip-final-newline/-/strip-final-newline-2.0.0.tgz 21040ms (cache revalidated)
226 http fetch GET 200 https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz 21060ms (cache revalidated)
227 http fetch GET 200 https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz 21098ms (cache revalidated)
228 http fetch GET 200 https://registry.npmjs.org/npm-run-path/-/npm-run-path-4.0.1.tgz 21105ms (cache revalidated)
229 http fetch GET 200 https://registry.npmjs.org/merge-stream/-/merge-stream-2.0.0.tgz 21040ms (cache revalidated)
230 http fetch GET 200 https://registry.npmjs.org/is-stream/-/is-stream-2.0.1.tgz 20319ms (cache revalidated)
231 http fetch GET 200 https://registry.npmjs.org/human-signals/-/human-signals-2.1.0.tgz 19572ms (cache revalidated)
232 http fetch GET 200 https://registry.npmjs.org/get-stream/-/get-stream-6.0.1.tgz 19284ms (cache revalidated)
233 http fetch GET 200 https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz 19222ms (cache revalidated)
234 http fetch GET 200 https://registry.npmjs.org/systeminformation/-/systeminformation-5.17.12.tgz 19392ms (cache revalidated)
235 http fetch GET 200 https://registry.npmjs.org/pick-port/-/pick-port-1.0.1.tgz 19602ms (cache revalidated)
236 http fetch GET 200 https://registry.npmjs.org/ffmpeg-for-homebridge/-/ffmpeg-for-homebridge-0.1.4.tgz 19551ms (cache revalidated)
237 http fetch GET 200 https://registry.npmjs.org/rxjs/-/rxjs-7.8.0.tgz 30239ms (cache revalidated)
238 http fetch GET 200 https://registry.npmjs.org/execa/-/execa-5.1.1.tgz 29993ms (cache revalidated)
239 http fetch GET 200 https://registry.npmjs.org/lodash.isequal/-/lodash.isequal-4.5.0.tgz 29948ms (cache revalidated)
240 http fetch GET 200 https://registry.npmjs.org/@homebridge/camera-utils/-/camera-utils-2.2.0.tgz 30717ms (cache revalidated)
241 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/chownr Completed in 38892ms
242 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/fs-minipass Completed in 39197ms
243 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/mimic-response Completed in 39189ms
244 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/decompress-response Completed in 39203ms
245 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/shebang-regex Completed in 39208ms
246 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/mimic-fn Completed in 39222ms
247 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/shebang-command Completed in 39247ms
248 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/strip-final-newline Completed in 39246ms
249 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/merge-stream Completed in 39236ms
250 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/path-key Completed in 39481ms
251 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/signal-exit Completed in 39477ms
252 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/onetime Completed in 39477ms
253 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/npm-run-path Completed in 39477ms
254 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/is-stream Completed in 39473ms
255 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/minizlib Completed in 39760ms
256 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/simple-concat Completed in 39727ms
257 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/ffmpeg-for-homebridge Completed in 39670ms
258 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/which Completed in 39921ms
259 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/get-stream Completed in 39889ms
260 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/lodash.isequal Completed in 40061ms
261 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/isexe Completed in 40361ms
262 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/minizlib/node_modules/minipass Completed in 40353ms
263 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/fs-minipass/node_modules/minipass Completed in 40346ms
264 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/detect-libc Completed in 40299ms
265 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/simple-get Completed in 40653ms
266 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/minipass Completed in 40727ms
267 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/pick-port Completed in 40614ms
268 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/cross-spawn Completed in 40766ms
269 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/mkdirp Completed in 41026ms
270 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/dotenv Completed in 41163ms
271 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/tslib Completed in 41466ms
272 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/execa Completed in 41482ms
273 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/human-signals Completed in 41690ms
274 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/@homebridge/camera-utils Completed in 43973ms
275 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/tar Completed in 44424ms
276 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/systeminformation Completed in 48342ms
277 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform Completed in 71309ms
278 timing reifyNode:node_modules/@0x5e/homebridge-tuya-platform/node_modules/rxjs Completed in 303055ms
279 timing reify:unpack Completed in 303244ms
280 timing reify:rollback:createSparse Completed in 24021ms
281 timing reify:rollback:retireShallow Completed in 55ms
282 timing command:install Completed in 378366ms
283 verbose stack Error: process terminated
283 verbose stack     at /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:199:39
283 verbose stack     at process.<anonymous> (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:53:5)
283 verbose stack     at process.emit (node:events:525:35)
284 verbose cwd /var/lib/homebridge
285 verbose Linux 5.15.76+
286 verbose node v18.12.1
287 verbose npm  v8.19.2
288 error process terminated
289 error signal SIGTERM
290 verbose exit 1
291 timing npm Completed in 384137ms
292 verbose unfinished npm timer reify 1678998106302
293 verbose code 1
294 error A complete log of this run can be found in:
294 error     /home/pi/.npm/_logs/2023-03-16T20_21_40_612Z-debug-0.log
```

### Other Infomations

After reinstallation , i will install the version but i have this error message. 

If i install V1.6.0 everything is fine. 
With V1.7.0Beta-30, No error message too.

**Comment by 0x5e** [comment]
Don't know why this would happend. Have you tried completely uninstall the plugin, and remove the folders in `./node_modules/@0x5e/homebridge-tuya-platform`?
