### ISSUE TITLE
TypeError: this.options.deviceOverrides is not iterable at TuyaPlatform.validateDeviceOverrides

### ISSUE THREAD

**Issue by miltykiss** [0x5e/homebridge-tuya-platform#279]
### Prerequisite

- [X] Yes

### Version

1.7.0-beta.35

### Device Control Mode

None

### Logs

```shell
[4/13/2023, 12:23:36 AM] [TuyaPlatform] Initializing TuyaPlatform platform...
[4/13/2023, 12:23:37 AM] TypeError: this.options.deviceOverrides is not iterable
    at TuyaPlatform.validateDeviceOverrides (/volume1/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:62:37)
    at TuyaPlatform.validate (/volume1/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:53:15)
    at new TuyaPlatform (/volume1/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:107:15)
    at /volume1/homebridge/node_modules/homebridge/src/server.ts:474:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/volume1/homebridge/node_modules/homebridge/src/server.ts:401:27)
    at Server.start (/volume1/homebridge/node_modules/homebridge/src/server.ts:176:29)
[4/13/2023, 12:23:37 AM] Got SIGTERM, shutting down Homebridge...
[4/13/2023, 12:23:37 AM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/volume1/homebridge/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/volume1/homebridge/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/volume1/homebridge/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:513:28)
    at process.emit (/volume1/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[4/13/2023, 12:23:42 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
```

### Other Information

This happens only after I restart Homebridge after installing beta 35. Rolling back to 1.6.0 seems to work.

I am running [Homebridge on a Synology NAS](https://github.com/oznu/homebridge-syno-spk)

**Comment by 0x5e** [comment]
is it working in beta.36?

**Comment by miltykiss** [comment]
> is it working in beta.36?

I'm sorry, I completely forgot to mention that this did work for me on beta.36

**Comment by 0x5e** [comment]
ok
