### ISSUE TITLE
 TypeError: this.device.remote_keys.key_list is not iterable

### ISSUE THREAD

**Issue by thanpaos** [0x5e/homebridge-tuya-platform#299]
### Prerequisite

- [X] Yes, I've read the readme completely.

### Cache

- [X] Yes, I've cleaned accessory cache and the issue still exists.

### Version

v1.7.0-beta.42

### Device Control Mode

None

### Logs

```shell
ypeError: this.device.remote_keys.key_list is not iterable
    at IRGenericAccessory.configureServices (/volume1/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/IRGenericAccessory.ts:12:47)
    at Function.createAccessory (/volume1/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/AccessoryFactory.ts:224:13)
    at TuyaPlatform.addAccessory (/volume1/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:427:40)
    at TuyaPlatform.initDevices (/volume1/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:195:12)
    at HomebridgeAPI.<anonymous> (/volume1/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:128:7)
```

### Other Infomations

Not sure how to fix this after update to new version. It used to work previously.

**Comment by 0x5e** [comment]
please enable homebridge debug mode and post api logs here, thanks.

**Comment by thanpaos** [comment]
[homebridge.log (1).txt](https://github.com/0x5e/homebridge-tuya-platform/files/11411291/homebridge.log.1.txt)

Here's the API log. Could you please help me to check.

**Comment by 0x5e** [comment]
Added some exception handling code, please try beta.43

**Comment by thanpaos** [comment]
Thank you for a very quick respond and update. 

Seems there's one device, IR remote S15pro is an issue. Is it not supported device ?

Product Name : S15ProCB3S红外遥控器
Product Category : wnykq

**Comment by 0x5e** [comment]
It displayed as "not supported" is because the IR Control Hub has no feature on homekit. It's normal behavior.
