### ISSUE TITLE
LED Strip RGBCCT seen as CW Light type

### ISSUE THREAD

**Issue by gcorly** [0x5e/homebridge-tuya-platform#311]
### Prerequisite

- [X] Yes, I've read the readme completely.

### Cache

- [X] Yes, I've cleaned accessory cache and the issue still exists.

### Version

v1.7.0-beta.45

### Device Infomation JSON File

```json
[
  {
    "active_time": 1684659200,
    "biz_type": 0,
    "category": "dd",
    "create_time": 1684658040,
    "icon": "smart/icon/ay1541056239985fDGjj/b0b60366ea58c5452c263ca3afe6ef4c.png",
    "id": "bf25a105a24248a34fddcl",
    "ip": "xx.xx.xx.xx",
    "lat": "xx.xxxx",
    "local_key": "xxxxxxxxxxxxxxxxxxxx",
    "lon": "x.xxxx",
    "model": "6125000100",
    "name": "Ruban LED",
    "online": true,
    "owner_id": "156524625",
    "product_id": "tdlcbgj5yipsqjlw",
    "product_name": "LSC Light Strip-RGBCCT",
    "status": [
      {
        "code": "bright_value",
        "value": 500
      },
      {
        "code": "colour_data",
        "value": "00b803e802b9"
      },
      {
        "code": "countdown",
        "value": 0
      },
      {
        "code": "mic_music_data",
        "value": "010000016432000003e8007803e800f003e8003c03e800b403e8012c03e8"
      },
      {
        "code": "scene_data",
        "value": "000e0d0000000000000000c80000"
      },
      {
        "code": "switch_led",
        "value": false
      },
      {
        "code": "temp_value",
        "value": 1000
      },
      {
        "code": "work_mode",
        "value": "colour"
      }
    ],
    "sub": false,
    "time_zone": "+02:00",
    "uid": "xxxxxxxxxxxxxxxx",
    "update_time": 1684690871,
    "uuid": "2d2e43b608108bb6",
    "schema": [
      {
        "code": "bright_value",
        "mode": "rw",
        "type": "Integer",
        "property": {
          "min": 10,
          "max": 1000,
          "scale": 0,
          "step": 1
        }
      },
      {
        "code": "colour_data",
        "mode": "rw",
        "type": "String",
        "property": {
          "maxlen": 255
        }
      },
      {
        "code": "control_data",
        "mode": "wo",
        "type": "String",
        "property": {
          "maxlen": 255
        }
      },
      {
        "code": "countdown",
        "mode": "rw",
        "type": "Integer",
        "property": {
          "unit": "s",
          "min": 0,
          "max": 86400,
          "scale": 0,
          "step": 1
        }
      },
      {
        "code": "mic_music_data",
        "mode": "rw",
        "type": "String",
        "property": {
          "maxlen": 255
        }
      },
      {
        "code": "music_data",
        "mode": "wo",
        "type": "String",
        "property": {
          "maxlen": 255
          }
      },
      {
        "code": "scene_data",
        "mode": "rw",
        "type": "String",
        "property": {
          "maxlen": 255
        }
      },
      {
        "code": "switch_led",
        "mode": "rw",
        "type": "Boolean",
        "property": {}
      },
      {
        "code": "temp_value",
        "mode": "rw",
        "type": "Integer",
        "property": {
          "min": 0,
          "max": 1000,
          "scale": 0,
          "step": 1
        }
      },
      {
        "code": "work_mode",
        "mode": "rw",
        "type": "Enum",
        "property": {
          "range": [
            "white",
            "colour",
            "scene",
            "music"
          ]
        }
      }
    ]
  }
]
```

### Device Control Mode

DP Instruction

### Logs

```shell
[5/22/2023, 9:17:07 PM] [TuyaPlatform] [TuyaOpenAPI] Request:
method = post
endpoint = https://openapi.tuyaeu.com
path = /v1.0/devices/bf25a105a24248a34fddcl/commands
query = null
headers = {
  "t": "1684783027072",
  "client_id": "arka39ppqdrn7kgfp7sv",
  "nonce": "eca6249c-a4cb-4d41-98df-a7cb84b1e878",
  "Signature-Headers": "client_id",
  "sign": "3B2485F3E8481AC1160EBD51A3E1926764021C1E8DB8D9F872BD8CDD0F428182",
  "sign_method": "HMAC-SHA256",
  "access_token": "a86a462229555f52d25c05e2ed3f42d3",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.7.0-beta.45"
}
body = {
  "commands": [
    {
      "code": "switch_led",
      "value": false
    }
  ]
}
[5/22/2023, 9:17:07 PM] [TuyaPlatform] [TuyaOpenAPI] Response:
path = /v1.0/devices/bf25a105a24248a34fddcl/commands
data = {
  "result": true,
  "success": true,
  "t": 1684783027207,
  "tid": "3e146581f8d511edb8e6f637b158923e"
}
[5/22/2023, 9:17:07 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/5954123818ebdcb00e3b69809e3a5f22
protocol = 4
message = {
  "dataId": "038c8e41-08dd-46ad-9e6d-e1ffd5230509",
  "devId": "bf25a105a24248a34fddcl",
  "productKey": "tdlcbgj5yipsqjlw",
  "status": [
    {
      "20": false,
      "code": "switch_led",
      "t": "1684783026",
      "value": false
    }
  ]
}
t = 1684783026
[5/22/2023, 9:17:10 PM] [TuyaPlatform] [TuyaOpenAPI] Request:
method = post
endpoint = https://openapi.tuyaeu.com
path = /v1.0/devices/bf25a105a24248a34fddcl/commands
query = null
headers = {
  "t": "1684783030744",
  "client_id": "arka39ppqdrn7kgfp7sv",
  "nonce": "46e7b84d-0778-4e42-9e91-1e411ac1c8e9",
  "Signature-Headers": "client_id",
  "sign": "245BBD659B27C5FC912A51DC3CA904A329A8BE68EDB1F3B95456D2193B946A9F",
  "sign_method": "HMAC-SHA256",
  "access_token": "a86a462229555f52d25c05e2ed3f42d3",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.7.0-beta.45"
}
body = {
  "commands": [
    {
      "code": "switch_led",
      "value": true
    }
  ]
}
[5/22/2023, 9:17:10 PM] [TuyaPlatform] [TuyaOpenAPI] Response:
path = /v1.0/devices/bf25a105a24248a34fddcl/commands
data = {
  "result": true,
  "success": true,
  "t": 1684783030940,
  "tid": "404532c7f8d511edb8e6f637b158923e"
}
[5/22/2023, 9:17:11 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/5954123818ebdcb00e3b69809e3a5f22
protocol = 4
message = {
  "dataId": "15a6db46-3bd2-4078-a4a3-97ea9f143f0b",
  "devId": "bf25a105a24248a34fddcl",
  "productKey": "tdlcbgj5yipsqjlw",
  "status": [
    {
      "20": true,
      "code": "switch_led",
      "t": "1684783030",
      "value": true
    }
  ]
}
t = 1684783030
[5/22/2023, 9:17:26 PM] [TuyaPlatform] [Ruban LED] Characteristic.ColorTemperature set to: 179
[5/22/2023, 9:17:26 PM] [TuyaPlatform] [TuyaOpenAPI] Request:
method = post
endpoint = https://openapi.tuyaeu.com
path = /v1.0/devices/bf25a105a24248a34fddcl/commands
query = null
headers = {
  "t": "1684783046607",
  "client_id": "arka39ppqdrn7kgfp7sv",
  "nonce": "a8cbd6ee-d86a-4f6f-9ad7-a9320b10fe32",
  "Signature-Headers": "client_id",
  "sign": "48052F68B20D88E87D379BE076BC698306024C4DF3F89C468203958CA67351D7",
  "sign_method": "HMAC-SHA256",
  "access_token": "a86a462229555f52d25c05e2ed3f42d3",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.7.0-beta.45"
}
body = {
  "commands": [
    {
      "code": "work_mode",
      "value": "white"
    },
    {
      "code": "temp_value",
      "value": 697
    }
  ]
}
[5/22/2023, 9:17:26 PM] [TuyaPlatform] [Ruban LED] Characteristic.ColorTemperature set to: 462
[5/22/2023, 9:17:26 PM] [TuyaPlatform] [TuyaOpenAPI] Response:
path = /v1.0/devices/bf25a105a24248a34fddcl/commands
data = {
  "result": true,
  "success": true,
  "t": 1684783046747,
  "tid": "49ba0954f8d511ed9b213e97a7ff9260"
}
[5/22/2023, 9:17:26 PM] [TuyaPlatform] [Ruban LED] Characteristic.ColorTemperature set to: 467
[5/22/2023, 9:17:26 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/5954123818ebdcb00e3b69809e3a5f22
protocol = 4
message = {
  "dataId": "1f5e3b56-6ba4-45ee-b6b9-383a7625d215",
  "devId": "bf25a105a24248a34fddcl",
  "productKey": "tdlcbgj5yipsqjlw",
  "status": [
    {
      "23": 697,
      "code": "temp_value",
      "t": "1684783046",
      "value": 697
    },
    {
      "21": "white",
      "code": "work_mode",
      "t": "1684783046",
      "value": "white"
    }
  ]
}
t = 1684783046
[5/22/2023, 9:17:26 PM] [TuyaPlatform] [Ruban LED] [Lightbulb/undefined/ColorTemperature] Update value: 467 => 179
[5/22/2023, 9:17:26 PM] [TuyaPlatform] [TuyaOpenAPI] Request:
method = post
endpoint = https://openapi.tuyaeu.com
path = /v1.0/devices/bf25a105a24248a34fddcl/commands
query = null
headers = {
  "t": "1684783046931",
  "client_id": "arka39ppqdrn7kgfp7sv",
  "nonce": "536e6496-9aae-4d79-9cd7-3ccbb73a886e",
  "Signature-Headers": "client_id",
  "sign": "DAE698D31F30C904CCF1F1A6D98CBE40EF5C60BA981EFD49F5105774BFAD0A0E",
  "sign_method": "HMAC-SHA256",
  "access_token": "a86a462229555f52d25c05e2ed3f42d3",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.7.0-beta.45"
}
body = {
  "commands": [
    {
      "code": "work_mode",
      "value": "white"
    },
    {
      "code": "temp_value",
      "value": 27
    }
  ]
}
[5/22/2023, 9:17:27 PM] [TuyaPlatform] [TuyaOpenAPI] Response:
path = /v1.0/devices/bf25a105a24248a34fddcl/commands
data = {
  "result": true,
  "success": true,
  "t": 1684783047078,
  "tid": "49ec7d48f8d511edb63796ce6b547e6f"
}
[5/22/2023, 9:17:27 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/5954123818ebdcb00e3b69809e3a5f22
protocol = 4
message = {
  "dataId": "d291eefa-507c-4cdb-9839-2095a3014598",
  "devId": "bf25a105a24248a34fddcl",
  "productKey": "tdlcbgj5yipsqjlw",
  "status": [
    {
      "23": 27,
      "code": "temp_value",
      "t": "1684783046",
      "value": 27
    }
  ]
}
t = 1684783046
[5/22/2023, 9:17:27 PM] [TuyaPlatform] [Ruban LED] [Lightbulb/undefined/ColorTemperature] Update value: 179 => 468
[5/22/2023, 9:17:29 PM] [TuyaPlatform] [Ruban LED] Characteristic.ColorTemperature set to: 429
[5/22/2023, 9:17:29 PM] [TuyaPlatform] [TuyaOpenAPI] Request:
method = post
endpoint = https://openapi.tuyaeu.com
path = /v1.0/devices/bf25a105a24248a34fddcl/commands
query = null
headers = {
  "t": "1684783049185",
  "client_id": "arka39ppqdrn7kgfp7sv",
  "nonce": "ae34e282-b086-4b80-8f76-4e9765470784",
  "Signature-Headers": "client_id",
  "sign": "99B808A157FD1F76D1EE58683F730E9FB5CED3B033F1134CE358D056D5C44E31",
  "sign_method": "HMAC-SHA256",
  "access_token": "a86a462229555f52d25c05e2ed3f42d3",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.7.0-beta.45"
}
body = {
  "commands": [
    {
      "code": "work_mode",
      "value": "white"
    },
    {
      "code": "temp_value",
      "value": 64
    }
  ]
}
[5/22/2023, 9:17:29 PM] [TuyaPlatform] [Ruban LED] Characteristic.ColorTemperature set to: 435
[5/22/2023, 9:17:29 PM] [TuyaPlatform] [TuyaOpenAPI] Response:
path = /v1.0/devices/bf25a105a24248a34fddcl/commands
data = {
  "result": true,
  "success": true,
  "t": 1684783049313,
  "tid": "4b42c378f8d511edb63796ce6b547e6f"
}
[5/22/2023, 9:17:29 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/5954123818ebdcb00e3b69809e3a5f22
protocol = 4
message = {
  "dataId": "cd00dae2-5c7a-437a-a5d4-f6be6f59b957",
  "devId": "bf25a105a24248a34fddcl",
  "productKey": "tdlcbgj5yipsqjlw",
  "status": [
    {
      "23": 64,
      "code": "temp_value",
      "t": "1684783048",
      "value": 64
    }
  ]
}
t = 1684783048
[5/22/2023, 9:17:29 PM] [TuyaPlatform] [Ruban LED] [Lightbulb/undefined/ColorTemperature] Update value: 435 => 429
[5/22/2023, 9:17:32 PM] [TuyaPlatform] [Ruban LED] Characteristic.ColorTemperature set to: 285
[5/22/2023, 9:17:32 PM] [TuyaPlatform] [Ruban LED] Characteristic.ColorTemperature set to: 284
[5/22/2023, 9:17:32 PM] [TuyaPlatform] [TuyaOpenAPI] Request:
method = post
endpoint = https://openapi.tuyaeu.com
path = /v1.0/devices/bf25a105a24248a34fddcl/commands
query = null
headers = {
  "t": "1684783052165",
  "client_id": "arka39ppqdrn7kgfp7sv",
  "nonce": "ab1b1f06-18e0-489f-8a9d-a80059ddee51",
  "Signature-Headers": "client_id",
  "sign": "E97EE39685E9B59F7D1B7BFAC55B7CEF47572E2BE8E2603403D2ADACE6E52D83",
  "sign_method": "HMAC-SHA256",
  "access_token": "a86a462229555f52d25c05e2ed3f42d3",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.7.0-beta.45"
}
body = {
  "commands": [
    {
      "code": "work_mode",
      "value": "white"
    },
    {
      "code": "temp_value",
      "value": 296
    }
  ]
}
[5/22/2023, 9:17:32 PM] [TuyaPlatform] [TuyaOpenAPI] Response:
path = /v1.0/devices/bf25a105a24248a34fddcl/commands
data = {
  "result": true,
  "success": true,
  "t": 1684783052305,
  "tid": "4d0afa3cf8d511ed9b213e97a7ff9260"
}
[5/22/2023, 9:17:32 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/5954123818ebdcb00e3b69809e3a5f22
protocol = 4
message = {
  "dataId": "27626bc0-2a9b-46a6-a2e0-e89ef0a51b4f",
  "devId": "bf25a105a24248a34fddcl",
  "productKey": "tdlcbgj5yipsqjlw",
  "status": [
    {
      "23": 296,
      "code": "temp_value",
      "t": "1684783051",
      "value": 296
    }
  ]
}
t = 1684783051
[5/22/2023, 9:18:06 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/5954123818ebdcb00e3b69809e3a5f22
protocol = 4
message = {
  "dataId": "d0ac1542-a3ee-4267-86d0-c5f8b4fcfc59",
  "devId": "bf25a105a24248a34fddcl",
  "productKey": "tdlcbgj5yipsqjlw",
  "status": [
    {
      "21": "colour",
      "code": "work_mode",
      "t": "1684783085",
      "value": "colour"
    }
  ]
}
t = 1684783085
[5/22/2023, 9:18:06 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/5954123818ebdcb00e3b69809e3a5f22
protocol = 4
message = {
  "dataId": "992b9619-33e6-4819-bbdd-476e51e8f1f4",
  "devId": "bf25a105a24248a34fddcl",
  "productKey": "tdlcbgj5yipsqjlw",
  "status": [
    {
      "24": "008303e802b9",
      "code": "colour_data",
      "t": "1684783085",
      "value": "008303e802b9"
    }
  ]
}
t = 1684783085
[5/22/2023, 9:18:07 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/5954123818ebdcb00e3b69809e3a5f22
protocol = 4
message = {
  "dataId": "163dcf26-9441-4dd6-8e07-8b9f1d05bc60",
  "devId": "bf25a105a24248a34fddcl",
  "productKey": "tdlcbgj5yipsqjlw",
  "status": [
    {
      "24": "006003e802b9",
      "code": "colour_data",
      "t": "1684783086",
      "value": "006003e802b9"
    }
  ]
}
t = 1684783086
[5/22/2023, 9:18:08 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/5954123818ebdcb00e3b69809e3a5f22
protocol = 4
message = {
  "dataId": "ec3db49c-10c0-4626-9d45-5f9d81b671eb",
  "devId": "bf25a105a24248a34fddcl",
  "productKey": "tdlcbgj5yipsqjlw",
  "status": [
    {
      "24": "003803e802b9",
      "code": "colour_data",
      "t": "1684783087",
      "value": "003803e802b9"
    }
  ]
}
t = 1684783087
[5/22/2023, 9:18:09 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/5954123818ebdcb00e3b69809e3a5f22
protocol = 4
message = {
  "dataId": "c479a851-1323-4428-9835-966d81854c6b",
  "devId": "bf25a105a24248a34fddcl",
  "productKey": "tdlcbgj5yipsqjlw",
  "status": [
    {
      "24": "001303e802b9",
      "code": "colour_data",
      "t": "1684783088",
      "value": "001303e802b9"
    }
  ]
}
t = 1684783088
[5/22/2023, 9:18:10 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/5954123818ebdcb00e3b69809e3a5f22
protocol = 4
message = {
  "dataId": "f5c86b3b-9317-4207-99ec-52dc739b5152",
  "devId": "bf25a105a24248a34fddcl",
  "productKey": "tdlcbgj5yipsqjlw",
  "status": [
    {
      "24": "014d03e802b9",
      "code": "colour_data",
      "t": "1684783089",
      "value": "014d03e802b9"
    }
  ]
}
t = 1684783089
[5/22/2023, 9:18:11 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/5954123818ebdcb00e3b69809e3a5f22
protocol = 4
message = {
  "dataId": "9c1e3894-4150-482c-a797-437b8e16bda8",
  "devId": "bf25a105a24248a34fddcl",
  "productKey": "tdlcbgj5yipsqjlw",
  "status": [
    {
      "24": "013703e802b9",
      "code": "colour_data",
      "t": "1684783090",
      "value": "013703e802b9"
    }
  ]
}
t = 1684783090
[5/22/2023, 9:18:12 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/5954123818ebdcb00e3b69809e3a5f22
protocol = 4
message = {
  "dataId": "c4056a50-492e-4728-851a-483d02dc91cd",
  "devId": "bf25a105a24248a34fddcl",
  "productKey": "tdlcbgj5yipsqjlw",
  "status": [
    {
      "24": "013703e803e8",
      "code": "colour_data",
      "t": "1684783091",
      "value": "013703e803e8"
    }
  ]
}
t = 1684783091
```

### Other Infomations

[5/22/2023, 8:56:37 PM] [TuyaPlatform] Got 1 device(s) and scene(s).
[5/22/2023, 8:56:37 PM] [TuyaPlatform] Device list saved at /var/lib/homebridge/persist/TuyaDeviceList.eu1684659099112nbCJu.json
[5/22/2023, 8:56:37 PM] [TuyaPlatform] Restoring existing accessory from cache: Ruban LED
[5/22/2023, 8:56:37 PM] [TuyaPlatform] [Ruban LED] Light type: CW
[5/22/2023, 8:56:37 PM] [TuyaPlatform] [Ruban LED] Adaptive Lighting disabled.

**Comment by gcorly** [comment]
the led strip is seen and on / off switch work, just an issue with the color, only have white (cold to warm) but no colors.
While through tuya app it's ok.
I first installed the old version of the plugin (homebridge-tuya-platform-talrhvfork v1.6.0) and the led strip was well seen with color changes... but after few hours, it stopped working so I uninstall everything, clean all and install yours..
and this one cannot see my accessory as a RGBCCT :(

thank you for your help

**Comment by 0x5e** [comment]
can you post some debug logs on 1.6.0 when you are setting colors? the `colour_data` of yours are old version (string type), in my memory 1.6.0 are not able to change it's color.

**Comment by gcorly** [comment]
I will try but as I said I used another plugin ( talrhv/tuya-homebridge - https://github.com/talrhv/tuya-homebridge) and after a few hours I have some issues in homebridge.
(I opened an issue but I think I won't have any answer as this plugin seem to be outdated..
That's why I saw yours and installed it)
I had JSON error even if I did not change anything in the plugin configuration.
it did not work anymore so I'm not sure I can install it again.
I did not enable the debug mode but maybe I can find some logs on homebridge ? (if you can telle me where ;))

I will see later when I'm back home

**Comment by gcorly** [comment]
> can you post some debug logs on 1.6.0 when you are setting colors? the `colour_data` of yours are old version (string type), in my memory 1.6.0 are not able to change it's color.

as I told you earlier, I don't understand why this plugin stopped to work. I tried again but it still failed.

you will find homebridge logs below, just in case you could find something...

TuyaOpenAPI response: {"result":{"access_token":"1c3c94d4902794b8febe705da2c9da91","expire_time":7200,"platform_url":"https://openapi.tuyaeu.com","refresh_token":"c6febdc6da161598b023cf873e2680fa","uid":"eu1684659099112nbCJu"},"success":true,"t":1684866534772,"tid":"ac751106f99711eda4908a3120fb3e2a"} path = /v1.0/iot-01/associated-users/actions/authorized-login
TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-01/associated-users/devices, params = {"size":100}, body = null, headers = {"t":"1684866534791","client_id":"arka39ppqdrn7kgfp7sv","nonce":"ab2833f0-f997-11ed-8220-8bca065b9f55","Signature-Headers":"client_id","sign":"63205283B992128C0C1CFA5C2EC7BFC6EE02746BCF64A0A4A0392215D974DDE5","sign_method":"HMAC-SHA256","access_token":"1c3c94d4902794b8febe705da2c9da91","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":{"devices":[{"active_time":1684659200,"biz_type":0,"category":"dd","create_time":1684658040,"icon":"smart/icon/ay1541056239985fDGjj/b0b60366ea58c5452c263ca3afe6ef4c.png","id":"bf25a105a24248a34fddcl","ip":"x.x.x.x","lat":"x.x","local_key":"xxxxxx","lon":"x.x","model":"6125000100","name":"Ruban LED","online":true,"owner_id":"156524625","product_id":"tdlcbgj5yipsqjlw","product_name":"LSC LED Strip RGBCCT 5m","status":[{"code":"switch_led","value":false},{"code":"work_mode","value":"colour"},{"code":"bright_value","value":500},{"code":"temp_value","value":296},{"code":"colour_data","value":"013703e803e8"},{"code":"scene_data","value":"000e0d0000000000000000c80000"},{"code":"countdown","value":0},{"code":"mic_music_data","value":"010000016432000003e8007803e800f003e8003c03e800b403e8012c03e8"}],"sub":false,"time_zone":"+02:00","uid":"xxxxx","update_time":1684783897,"uuid":"2d2e43b608108bb6"}],"last_row_key":"C7DDABB1B880373A3847D2D20D11BB58","total":1},"success":true,"t":1684866534907,"tid":"ac8c5953f99711eda4908a3120fb3e2a"} path = /v1.0/iot-01/associated-users/devices
TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyaeu.com, path = /v1.0/devices/functions, params = {"device_ids":"bf25a105a24248a34fddcl"}, body = null, headers = {"t":"1684866534918","client_id":"arka39ppqdrn7kgfp7sv","nonce":"ab2833f0-f997-11ed-8220-8bca065b9f55","Signature-Headers":"client_id","sign":"275900B342CA6D85599E86373C4F87355CFB6BC255E45EBBF82B52C519241DD4","sign_method":"HMAC-SHA256","access_token":"1c3c94d4902794b8febe705da2c9da91","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
TuyaOpenAPI response: {"result":[{"category":"dd","devices":["bf25a105a24248a34fddcl"],"functions":[{"code":"switch_led","desc":"switch led","name":"switch led","type":"Boolean","values":"{}"},{"code":"work_mode","desc":"work mode","name":"work mode","type":"Enum","values":"{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"},{"code":"bright_value","desc":"bright value","name":"bright value","type":"Integer","values":"{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"temp_value","desc":"temp value","name":"temp value","type":"Integer","values":"{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"colour_data","desc":"colour data","name":"colour data","type":"String","values":"{\"maxlen\":255}"},{"code":"scene_data","desc":"scene data","name":"scene data","type":"String","values":"{\"maxlen\":255}"},{"code":"countdown","desc":"countdown","name":"countdown","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"music_data","desc":"music data","name":"music data","type":"String","values":"{\"maxlen\":255}"},{"code":"control_data","desc":"control data","name":"control data","type":"String","values":"{\"maxlen\":255}"},{"code":"mic_music_data","desc":"mic music data","name":"mic music data","type":"String","values":"{\"maxlen\":255}"}],"product_id":"tdlcbgj5yipsqjlw"}],"success":true,"t":1684866535042,"tid":"aca30ccef99711eda795ce4cada2c678"} path = /v1.0/devices/functions
Adding: Ruban LED (dd / bf25a105a24248a34fddcl)
Existing Accessory found Ruban LED  bf25a105a24248a34fddcl bd9577ea-a241-426d-a096-03a173a82980
[5/23/2023, 8:28:55 PM] SyntaxError: Unexpected number in JSON at position 1
    at JSON.parse (<anonymous>)
    at LightAccessory.refreshAccessoryServiceIfNeed (/var/lib/homebridge/node_modules/homebridge-tuya-platform-talrhvfork/lib/light_accessory.js:70:103)
    at new LightAccessory (/var/lib/homebridge/node_modules/homebridge-tuya-platform-talrhvfork/lib/light_accessory.js:32:10)
    at TuyaPlatform.addAccessory (/var/lib/homebridge/node_modules/homebridge-tuya-platform-talrhvfork/index.js:140:27)
    at TuyaPlatform.initTuyaSDK (/var/lib/homebridge/node_modules/homebridge-tuya-platform-talrhvfork/index.js:104:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by gcorly** [comment]
> can you post some debug logs on 1.6.0 when you are setting colors? the `colour_data` of yours are old version (string type), in my memory 1.6.0 are not able to change it's color.

Hello @0x5e, do you have any clue or anything else about this issue ?
How can I help you ?

**Comment by 0x5e** [comment]
the `colour_data` type of your device is string, it's not supported yet. I will support this when I'm free. apologize for my busy these days :(

**Comment by gcorly** [comment]
Thank you. don't worry, i'm not in a hurry and i understand that you may be busy with other things. i just wanted to know if i could bring you any other information to help you.
In the meantime, I've chosen a scene from Tuya and I'm just using the on/off switch from Homebridge, so I can wait.  ;)

**Comment by gcorly** [comment]
Hi, 
do you have any clue in order to add this color_data type ?
thank you

**Comment by gcorly** [comment]
I don't know how I can help you.
Do you want me to make some manipulations which could help you ?
