### ISSUE TITLE
TypeError: status is not iterable

### ISSUE THREAD

**Issue by Claywd** [0x5e/homebridge-tuya-platform#341]
### Prerequisite

- [X] Yes, I've read the readme completely.

### Cache

- [X] Yes, I've cleaned accessory cache and the issue still exists.

### Version

v1.5.0

### Device Infomation JSON File

```json
couldn't find this anywhere.
```

### Device Control Mode

Standard Instruction

### Logs

```shell
TuyaOpenAPI response: {"result":{"devices":[{"active_time":1686520289,"biz_type":0,"category":"szjqr","create_time":1686520289,"icon":"smart/icon/ay15327721968035jwx9/ebd32104d767e65fb9561f1210d31eaf.png","id":"eb0e4d8063107ac1d9yxmw","ip":"","lat":"30.3900","local_key":">uO>d'ch|hwWeG)S","lon":"-98.0200","model":"BS-FB-V3","name":"Mac Pro","node_id":"tuya47d51b848e39","online":true,"owner_id":"60529943","product_id":"rvdceqjh","product_name":"ZC-ADP 手指机器人","status":[{"code":"switch","value":true},{"code":"mode","value":"click"},{"code":"arm_down_percent","value":90},{"code":"click_sustain_time","value":5},{"code":"battery_percentage","value":70},{"code":"arm_up_percent","value":0},{"code":"tap_enable","value":true}],"sub":true,"time_zone":"-05:00","uid":"az1641084460152rO7Jh","update_time":1689561862,"uuid":"tuya47d51b848e39"},{"active_time":1687130315,"biz_type":0,"category":"dj","create_time":1687130315,"icon":"smart/icon/ay1565741189760sQJTr/27510c110be9b9cc5a8124661919fb35.png","id":"eb325fa5538b38759fwyx6","ip":"72.177.107.196","lat":"","local_key":"-@o#{`|(TcU9-.}@","lon":"","model":"120V","name":"Window Light","online":false,"owner_id":"60529943","product_id":"c0raacap0zsw7gq8","product_name":"60W A19 Filament","status":[{"code":"switch_led","value":true},{"code":"work_mode","value":"white"},{"code":"bright_value_v2","value":1000},{"code":"temp_value_v2","value":287},{"code":"scene_data_v2","value":"{\"scene_num\":1,\"scene_units\":[{\"bright\":500,\"h\":0,\"s\":0,\"temperature\":0,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":50,\"unit_switch_duration\":50,\"v\":0}]}"},{"code":"countdown_1","value":0},{"code":"control_data","value":""},{"code":"rhythm_mode","value":"AAAAAAA="},{"code":"sleep_mode","value":"AAA="},{"code":"wakeup_mode","value":"AAA="},{"code":"remote_switch","value":true},{"code":"random_timing","value":"AAAA"}],"sub":false,"time_zone":"-05:00","uid":"az1641084460152rO7Jh","update_time":1689546596,"uuid":"6fae3acfb9b93c34"},{"active_time":1686520154,"biz_type":0,"category":"cz","create_time":1686444747,"icon":"smart/icon/ay1552546478455PA09B/16536201369942f47a15b.png","id":"ebe7c706871b1e6f79iakq","ip":"72.177.107.196","lat":"30.3900","local_key":">uO>d'ch|hwWeG)S","lon":"-98.0200","model":"CR3L蓝牙网关，支持128子设备 ","name":"Bluetooth Gateway","online":true,"owner_id":"60529943","product_id":"csvxfq3ecmedidkh","product_name":"NH-YM  蓝牙mesh网关 更新版","sub":true,"time_zone":"-05:00","uid":"az1641084460152rO7Jh","update_time":1689492352,"uuid":"d1dde88c9f725bcd"},{"active_time":1641084527,"biz_type":0,"category":"dj","create_time":1632097663,"icon":"smart/icon/ay1565741189760sQJTr/387c84763dacf515803027f54f42ba3b.png","id":"eb5939b3ac3a89bf35zivb","ip":"72.177.107.196","lat":"30.3918","local_key":"9a9726327b0c728b","lon":"-98.0202","model":"120V","name":"60W ST19 Filament 2","online":true,"owner_id":"60529943","product_id":"sjlkbyftxuodi4wv","product_name":"60W ST19 Filament","status":[{"code":"switch_led","value":false},{"code":"work_mode","value":"white"},{"code":"bright_value_v2","value":158},{"code":"temp_value_v2","value":227},{"code":"scene_data_v2","value":"{\"scene_num\":1,\"scene_units\":[{\"bright\":500,\"h\":0,\"s\":0,\"temperature\":0,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":50,\"unit_switch_duration\":50,\"v\":0}]}"},{"code":"countdown_1","value":0},{"code":"control_data","value":""},{"code":"rhythm_mode","value":"AAAAAAA="},{"code":"sleep_mode","value":"AAA="},{"code":"wakeup_mode","value":"AAA="},{"code":"remote_switch","value":true},{"code":"cycle_timing","value":"AAAA"},{"code":"random_timing","value":"AAAA"}],"sub":false,"time_zone":"-06:00","uid":"az1641084460152rO7Jh","update_time":1689267554,"uuid":"b7fd3cd6d77a3c0f"},{"active_time":1641084539,"biz_type":0,"category":"dj","create_time":1632097617,"icon":"smart/icon/ay1565741189760sQJTr/387c84763dacf515803027f54f42ba3b.png","id":"ebcd848d2f7fabfa50pjfa","ip":"72.177.107.196","lat":"30.3918","local_key":"1ad1174d794a6ac6","lon":"-98.0202","model":"120V","name":"60W ST19 Filament 3","online":true,"owner_id":"60529943","product_id":"sjlkbyftxuodi4wv","product_name":"60W ST19 Filament","status":[{"code":"switch_led","value":false},{"code":"work_mode","value":"white"},{"code":"bright_value_v2","value":158},{"code":"temp_value_v2","value":227},{"code":"scene_data_v2","value":"{\"scene_num\":1,\"scene_units\":[{\"bright\":500,\"h\":0,\"s\":0,\"temperature\":0,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":50,\"unit_switch_duration\":50,\"v\":0}]}"},{"code":"countdown_1","value":0},{"code":"control_data","value":""},{"code":"rhythm_mode","value":"AAAAAAA="},{"code":"sleep_mode","value":"AAA="},{"code":"wakeup_mode","value":"AAA="},{"code":"remote_switch","value":true},{"code":"cycle_timing","value":"AAAA"},{"code":"random_timing","value":"AAAA"}],"sub":false,"time_zone":"-06:00","uid":"az1641084460152rO7Jh","update_time":1689032132,"uuid":"cc07f2fad8bed6d1"},{"active_time":1687259628,"biz_type":0,"category":"dj","create_time":1687259628,"icon":"smart/icon/ay1565741189760sQJTr/ae8f582b28ff5663c14542ff126d7e40.png","id":"eb6691b8a094330ac7ej2w","ip":"72.177.107.196","lat":"","local_key":"F<[k;%BJlg~{zDfW","lon":"","model":"120V","name":"40W Globe Filament","online":true,"owner_id":"60529943","product_id":"gwusdk1ipjecqyia","product_name":"40W Globe Filament","status":[{"code":"switch_led","value":false},{"code":"work_mode","value":"white"},{"code":"bright_value_v2","value":1000},{"code":"temp_value_v2","value":334},{"code":"scene_data_v2","value":"{\"scene_num\":1,\"scene_units\":[{\"bright\":500,\"h\":0,\"s\":0,\"temperature\":0,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":50,\"unit_switch_duration\":50,\"v\":0}]}"},{"code":"countdown_1","value":0},{"code":"control_data","value":""},{"code":"rhythm_mode","value":"AAAAAAA="},{"code":"sleep_mode","value":"AAA="},{"code":"wakeup_mode","value":"AAA="},{"code":"remote_switch","value":true},{"code":"random_timing","value":"AAAA"}],"sub":false,"time_zone":"-05:00","uid":"az1641084460152rO7Jh","update_time":1688544231,"uuid":"58cd7be60440add2"},{"active_time":1641084515,"biz_type":0,"category":"dj","create_time":1632097134,"icon":"smart/icon/ay1565741189760sQJTr/387c84763dacf515803027f54f42ba3b.png","id":"eb77c450cf36029395sdxg","ip":"72.177.107.196","lat":"30.3918","local_key":"efa7867b2ffe658b","lon":"-98.0202","model":"120V","name":"60W ST19 Filament","online":true,"owner_id":"60529943","product_id":"sjlkbyftxuodi4wv","product_name":"60W ST19 Filament","status":[{"code":"switch_led","value":false},{"code":"work_mode","value":"white"},{"code":"bright_value_v2","value":158},{"code":"temp_value_v2","value":227},{"code":"scene_data_v2","value":"{\"scene_num\":1,\"scene_units\":[{\"bright\":500,\"h\":0,\"s\":0,\"temperature\":0,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":50,\"unit_switch_duration\":50,\"v\":0}]}"},{"code":"countdown_1","value":0},{"code":"control_data","value":""},{"code":"rhythm_mode","value":"AAAAAAA="},{"code":"sleep_mode","value":"AAA="},{"code":"wakeup_mode","value":"AAA="},{"code":"remote_switch","value":true},{"code":"cycle_timing","value":"AAAA"},{"code":"random_timing","value":"AAAA"}],"sub":false,"time_zone":"-06:00","uid":"az1641084460152rO7Jh","update_time":1688544223,"uuid":"46b240f49afcd608"},{"active_time":1641084551,"biz_type":0,"category":"dj","create_time":1632097743,"icon":"smart/icon/ay1565741189760sQJTr/387c84763dacf515803027f54f42ba3b.png","id":"eb77a1caebfccdf6cepitz","ip":"72.177.107.196","lat":"30.3918","local_key":"9b5ab8378bfdc14c","lon":"-98.0202","model":"120V","name":"60W ST19 Filament 4","online":true,"owner_id":"60529943","product_id":"sjlkbyftxuodi4wv","product_name":"60W ST19 Filament","status":[{"code":"switch_led","value":false},{"code":"work_mode","value":"white"},{"code":"bright_value_v2","value":158},{"code":"temp_value_v2","value":227},{"code":"scene_data_v2","value":"{\"scene_num\":1,\"scene_units\":[{\"bright\":500,\"h\":0,\"s\":0,\"temperature\":0,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":50,\"unit_switch_duration\":50,\"v\":0}]}"},{"code":"countdown_1","value":0},{"code":"control_data","value":""},{"code":"rhythm_mode","value":"AAAAAAA="},{"code":"sleep_mode","value":"AAA="},{"code":"wakeup_mode","value":"AAA="},{"code":"remote_switch","value":true},{"code":"cycle_timing","value":"AAAA"},{"code":"random_timing","value":"AAAA"}],"sub":false,"time_zone":"-06:00","uid":"az1641084460152rO7Jh","update_time":1688544214,"uuid":"208a351446f00023"}],"hsa_more":false,"last_row_key":"16B252DE4110B83AFC05EAA8EA53DE4F","total":8},"success":true,"t":1689562163743,"tid":"895ff487244c11ee804ade073cb82c5d"} path = /v1.0/iot-01/associated-users/devices
TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyaus.com, path = /v1.0/devices/functions, params = {"device_ids":"eb0e4d8063107ac1d9yxmw,eb325fa5538b38759fwyx6,ebe7c706871b1e6f79iakq,eb5939b3ac3a89bf35zivb,ebcd848d2f7fabfa50pjfa,eb6691b8a094330ac7ej2w,eb77c450cf36029395sdxg,eb77a1caebfccdf6cepitz"}, body = null, headers = {"t":"1689562163863","client_id":"tfwasppmjvtcwuvatc99","nonce":"88e4bb30-244c-11ee-865c-29926badb61d","Signature-Headers":"client_id","sign":"CDC5D1B48E2C6084E2B24B4D1E3ACE52DCFD768D98B868D5ED8CC4D71C450084","sign_method":"HMAC-SHA256","access_token":"be6525f9403868450d0c5aeec05e6d78","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
[7/16/2023, 9:49:23 PM] [Garage Door] Restoring existing accessory from cache: garage
TuyaOpenAPI response: {"result":[{"category":"szjqr","devices":["eb0e4d8063107ac1d9yxmw"],"functions":[{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"},{"code":"mode","desc":"mode","name":"mode","type":"Enum","values":"{\"range\":[\"click\",\"switch\"]}"},{"code":"arm_down_percent","desc":"arm down percent","name":"arm down percent","type":"Integer","values":"{\"unit\":\"\",\"min\":51,\"max\":100,\"scale\":0,\"step\":1}"},{"code":"click_sustain_time","desc":"click sustain time","name":"click sustain time","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":10,\"scale\":0,\"step\":1}"},{"code":"arm_up_percent","desc":"arm up percent","name":"arm up percent","type":"Integer","values":"{\"min\":0,\"max\":50,\"scale\":0,\"step\":1}"},{"code":"tap_enable","desc":"tap enable","name":"tap enable","type":"Boolean","values":"{}"}],"product_id":"rvdceqjh"},{"category":"dj","devices":["eb5939b3ac3a89bf35zivb","ebcd848d2f7fabfa50pjfa","eb77c450cf36029395sdxg","eb77a1caebfccdf6cepitz"],"functions":[{"code":"switch_led","desc":"switch led","name":"switch led","type":"Boolean","values":"{}"},{"code":"work_mode","desc":"work mode","name":"work mode","type":"Enum","values":"{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"},{"code":"bright_value_v2","desc":"bright value v2","name":"bright value v2","type":"Integer","values":"{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"temp_value_v2","desc":"temp value v2","name":"temp value v2","type":"Integer","values":"{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"scene_data_v2","desc":"scene data v2","name":"scene data v2","type":"Json","values":"{\"scene_num\":{\"min\":1,\"scale\":0,\"max\":8,\"step\":1},\"scene_units\": {\"unit_change_mode\":{\"range\":[\"static\",\"jump\",\"gradient\"]},\"unit_switch_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"unit_gradient_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"bright\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"temperature\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"control_data","desc":"control data","name":"control data","type":"Json","values":"{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"},{"code":"rhythm_mode","desc":"rhythm mode","name":"rhythm mode","type":"Raw","values":"{\"maxlen\":255}"},{"code":"sleep_mode","desc":"sleep mode","name":"sleep mode","type":"Raw","values":"{\"maxlen\":255}"},{"code":"wakeup_mode","desc":"wakeup mode","name":"wakeup mode","type":"Raw","values":"{\"maxlen\":255}"},{"code":"remote_switch","desc":"remote switch","name":"remote switch","type":"Boolean","values":"{}"},{"code":"cycle_timing","desc":"cycle timing","name":"cycle timing","type":"Raw","values":"{}"},{"code":"random_timing","desc":"random timing","name":"random timing","type":"Raw","values":"{}"}],"product_id":"sjlkbyftxuodi4wv"},{"category":"dj","devices":["eb325fa5538b38759fwyx6"],"functions":[{"code":"switch_led","desc":"switch led","name":"switch led","type":"Boolean","values":"{}"},{"code":"work_mode","desc":"work mode","name":"work mode","type":"Enum","values":"{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"},{"code":"bright_value_v2","desc":"bright value v2","name":"bright value v2","type":"Integer","values":"{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"temp_value_v2","desc":"temp value v2","name":"temp value v2","type":"Integer","values":"{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"scene_data_v2","desc":"scene data v2","name":"scene data v2","type":"Json","values":"{\"scene_num\":{\"min\":1,\"scale\":0,\"max\":8,\"step\":1},\"scene_units\": {\"unit_change_mode\":{\"range\":[\"static\",\"jump\",\"gradient\"]},\"unit_switch_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"unit_gradient_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"bright\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"temperature\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"control_data","desc":"control data","name":"control data","type":"Json","values":"{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"},{"code":"rhythm_mode","desc":"rhythm mode","name":"rhythm mode","type":"Raw","values":"{\"maxlen\":255}"},{"code":"sleep_mode","desc":"sleep mode","name":"sleep mode","type":"Raw","values":"{\"maxlen\":255}"},{"code":"wakeup_mode","desc":"wakeup mode","name":"wakeup mode","type":"Raw","values":"{\"maxlen\":255}"},{"code":"remote_switch","desc":"remote switch","name":"remote switch","type":"Boolean","values":"{}"},{"code":"random_timing","desc":"random timing","name":"random timing","type":"Raw","values":"{}"}],"product_id":"c0raacap0zsw7gq8"},{"category":"dj","devices":["eb6691b8a094330ac7ej2w"],"functions":[{"code":"switch_led","desc":"switch led","name":"switch led","type":"Boolean","values":"{}"},{"code":"work_mode","desc":"work mode","name":"work mode","type":"Enum","values":"{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"},{"code":"bright_value_v2","desc":"bright value v2","name":"bright value v2","type":"Integer","values":"{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"temp_value_v2","desc":"temp value v2","name":"temp value v2","type":"Integer","values":"{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"scene_data_v2","desc":"scene data v2","name":"scene data v2","type":"Json","values":"{\"scene_num\":{\"min\":1,\"scale\":0,\"max\":8,\"step\":1},\"scene_units\": {\"unit_change_mode\":{\"range\":[\"static\",\"jump\",\"gradient\"]},\"unit_switch_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"unit_gradient_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"bright\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"temperature\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"control_data","desc":"control data","name":"control data","type":"Json","values":"{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"},{"code":"rhythm_mode","desc":"rhythm mode","name":"rhythm mode","type":"Raw","values":"{\"maxlen\":255}"},{"code":"sleep_mode","desc":"sleep mode","name":"sleep mode","type":"Raw","values":"{\"maxlen\":255}"},{"code":"wakeup_mode","desc":"wakeup mode","name":"wakeup mode","type":"Raw","values":"{\"maxlen\":255}"},{"code":"remote_switch","desc":"remote switch","name":"remote switch","type":"Boolean","values":"{}"},{"code":"random_timing","desc":"random timing","name":"random timing","type":"Raw","values":"{}"}],"product_id":"gwusdk1ipjecqyia"}],"success":true,"t":1689562164278,"tid":"89b537b1244c11ee9fecaa50f188a4b0"} path = /v1.0/devices/functions
Adding: Mac Pro (szjqr / eb0e4d8063107ac1d9yxmw)
Adding: Window Light (dj / eb325fa5538b38759fwyx6)
Existing Accessory found Window Light  eb325fa5538b38759fwyx6 4dafaf04-a1ba-4f28-9d25-c8c311508036
Adding: Bluetooth Gateway (cz / ebe7c706871b1e6f79iakq)

/homebridge/node_modules/homebridge-tuya-platform/util/datautil.js:6
        for (var map of status) {
                        ^
TypeError: status is not iterable
    at DataUtil.getSubService (/homebridge/node_modules/homebridge-tuya-platform/util/datautil.js:6:25)
    at TuyaPlatform.addAccessory (/homebridge/node_modules/homebridge-tuya-platform/index.js:137:41)
    at TuyaPlatform.initTuyaSDK (/homebridge/node_modules/homebridge-tuya-platform/index.js:99:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Other Infomations

This happened when I added the finger bot and fingerbot gateway to the tuya app... I tried disassociating the gateway with my cloud project but that didn't help either.

**Comment by 0x5e** [comment]
version 1.5.0 is official plugin, not this project. please accoring to readme if you want to install the beta version.
