### ISSUE TITLE
Plugin completely crashes from device all of a sudden

### ISSUE THREAD

**Issue by Aransh** [0x5e/homebridge-tuya-platform#505]
### Prerequisite

- [X] Yes, I've read the readme completely.

### Cache

- [X] Yes, I've cleaned accessory cache and the issue still exists.

### Version

1.7.0-beta.54

### Device Infomation JSON File

```json
Not available
```

### Device Control Mode

None

### Logs

```shell
[11/3/2024, 11:49:43 PM] Homebridge v1.8.5 (HAP v0.12.3) (Homebridge 819E) is running on port 51274.
[11/3/2024, 11:49:43 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[11/3/2024, 11:49:45 PM] [Tuya] [TuyaOpenAPI] Response:
path = /v1.0/iot-01/associated-users/actions/authorized-login
data = {
  "result": {
    "access_token": "XXXXXXXXXXXX",
    "expire_time": 7200,
    "platform_url": "https://openapi.tuyaeu.com",
    "refresh_token": "XXXXXXXXXXXX",
    "uid": "eu1693254885394qufBT"
  },
  "success": true,
  "t": 1730670585276,
  "tid": "8a0c80419a2d11ef894136243096d294"
}
[11/3/2024, 11:49:45 PM] [Tuya] Start MQTT connection.
[11/3/2024, 11:49:45 PM] [Tuya] Fetching home list.
[11/3/2024, 11:49:45 PM] [Tuya] [TuyaOpenAPI] Request:
method = post
endpoint = https://openapi.tuyaeu.com
path = /v1.0/iot-03/open-hub/access-config
query = null
headers = {
  "t": "1730670585641",
  "client_id": "XXXXXXXXXXXX",
  "nonce": "d0eb8e73-cd00-48dd-8235-029679a8f92a",
  "Signature-Headers": "client_id",
  "sign": "B992E65D03077E564B5CB184DD4A99AF56E5DD088E3C2E3192260D5157CF78BE",
  "sign_method": "HMAC-SHA256",
  "access_token": "XXXXXXXXXXXX",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.7.0-beta.54"
}
body = {
  "uid": "eu1693254885394qufBT",
  "link_id": "04de9f54-2fc8-4888-b16c-fb7cd1ef08a9",
  "link_type": "mqtt",
  "topics": "device",
  "msg_encrypted_version": "1.0"
}
[11/3/2024, 11:49:45 PM] [Tuya] [TuyaOpenAPI] Request:
method = get
endpoint = https://openapi.tuyaeu.com
path = /v1.0/users/eu1693254885394qufBT/homes
query = undefined
headers = {
  "t": "1730670585643",
  "client_id": "XXXXXXXXXXXX",
  "nonce": "2d2d9b7b-1e34-4893-b8a8-6dcf37be4486",
  "Signature-Headers": "client_id",
  "sign": "0B47FA12B2D38405F890989F265599CDA6AB40BBC55FAABCCA16F2BB620755DD",
  "sign_method": "HMAC-SHA256",
  "access_token": "XXXXXXXXXXXX",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.7.0-beta.54"
}
body = null
[11/3/2024, 11:49:45 PM] [Tuya] [TuyaOpenAPI] Response:
path = /v1.0/iot-03/open-hub/access-config
data = {
  "result": {
    "client_id": "cloud_newa89fd52ebd6add44e842cdf169f6efdb",
    "expire_time": 7200,
    "password": "XXXXXXXXXXXX",
    "sink_topic": {
      "device": "cloud/token/out/{device_id}"
    },
    "source_topic": {
      "device": "cloud/token/in/new7d5d31af85cdfe9ccc01e027b034965e"
    },
    "url": "ssl://m1.tuyaeu.com:8883",
    "username": "cloud_new7d5d31af85cdfe9ccc01e027b034965e"
  },
  "success": true,
  "t": 1730670585712,
  "tid": "8a54cd309a2d11efbfa92a8db75a9554"
}
[11/3/2024, 11:49:45 PM] [Tuya] [TuyaOpenAPI] Response:
path = /v1.0/users/eu1693254885394qufBT/homes
data = {
  "result": [
    {
      "geo_name": "Kalaniyot Commercial Center Ashdod",
      "home_id": 164818273,
      "lat": 31.783594190070936,
      "lon": 34.65404930312776,
      "name": "Yakinton",
      "role": "OWNER"
    }
  ],
  "success": true,
  "t": 1730670585900,
  "tid": "8a7317809a2d11efbfa92a8db75a9554"
}
[11/3/2024, 11:49:45 PM] [Tuya] Got home_id=164818273, name=Yakinton
[11/3/2024, 11:49:45 PM] [Tuya] Fetching device list.
[11/3/2024, 11:49:45 PM] [Tuya] [TuyaOpenAPI] Request:
method = get
endpoint = https://openapi.tuyaeu.com
path = /v1.0/homes/164818273/devices
query = undefined
headers = {
  "t": "1730670585947",
  "client_id": "XXXXXXXXXXXX",
  "nonce": "93fd7300-fccb-4a43-bb0f-b561c17a8de0",
  "Signature-Headers": "client_id",
  "sign": "EF3C6CA3F8B0D2D9E87CDB7542E9E53EDFAD687CA1559204E07738076E7C56A2",
  "sign_method": "HMAC-SHA256",
  "access_token": "XXXXXXXXXXXX",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.7.0-beta.54"
}
body = null
[11/3/2024, 11:49:46 PM] [Tuya] [TuyaOpenAPI] Response:
path = /v1.0/homes/164818273/devices
data = {
  "code": 501,
  "msg": "request fail with unkown error",
  "success": false,
  "t": 1730670586060,
  "tid": "8a8228709a2d11ef894136243096d294"
}
[11/3/2024, 11:49:46 PM] TypeError: Cannot read properties of undefined (reading 'map')
    at TuyaHomeDeviceManager.updateDevices (/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/device/TuyaHomeDeviceManager.ts:21:51)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TuyaPlatform.initHomeProject (/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:397:21)
    at TuyaPlatform.initDevices (/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:154:17)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/platform.ts:128:7)
[11/3/2024, 11:49:46 PM] Got SIGTERM, shutting down Homebridge...
```

### Other Infomations

Been using the plugin for over a year now with no issues, suddenly today my light switch appeared as unavailable on HomeKit. Trying to toggle it showed it was offline on homebridge logs (which was not true as it was controllable on the smart life app). Restarting the commenting server eventually lead to the plugging repeatedly crashing with error message `TypeError: Cannot read properties of undefined (reading 'map') `
Only way I have managed to get out to stop crashing was completely removing the light switch from the smart life app, but adding it again immediately causes the plugin to crash… I’m really not sure what could cause this as I haven’t touched the homebridge configuration at all before this started, maybe server side issue/update on Tuya API?
Either way any help would be greatly appreciated 🙏

**Comment by Aransh** [comment]
Possibly related, I've noticed that even when connected to the smart life app (and again, fully working with the app), it does not appear at all under the Tuya developer platform devices tab, where I am 100% sure it did show up before this issue started...

This is the switch in case this helps (1 gang version) -
https://a.aliexpress.com/_oknuc5d

**Comment by Aransh** [comment]
Must've been a weird server-side issue... After removing the device from my account and waiting a few hours, it finally cleared from my cloud account, and then adding it again it got back to working!
